-- =============================================================================
-- TABLE: DD_SORTER_BATCH_CARGA_CTRL
-- Exportado de CD2@2026-07-06 (fonte: banco remoto)
-- =============================================================================

CREATE TABLE "CD2"."DD_SORTER_BATCH_CARGA_CTRL" 
   (	"NROCARGA" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20) NOT NULL ENABLE, 
	"WORKER_ID" VARCHAR2(30), 
	"PRIORIDADE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"VOLS_ELEGIVEIS" NUMBER, 
	"DTA_INCLUSAO" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DTA_CLAIM" DATE, 
	"DTA_ULTIMO_CICLO" DATE, 
	"DTA_CONCLUSAO" DATE, 
	"OBS" VARCHAR2(500), 
	 CONSTRAINT "CK_DD_SORTER_BATCH_CARGA_ST" CHECK (
    STATUS IN ('PENDENTE', 'PROCESSANDO', 'CONCLUIDA', 'ERRO')
  ) ENABLE, 
	 CONSTRAINT "PK_DD_SORTER_BATCH_CARGA" PRIMARY KEY ("NROCARGA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSD_CONSINCO"  ENABLE
   ))
  TABLESPACE "TSD_CONSINCO"
