-- =============================================================================
-- TABLE: DD_SORTER_EVENTO_CTRL
-- Exportado de CD2@2026-07-01 (fonte: banco remoto)
-- =============================================================================

CREATE TABLE "CD2"."DD_SORTER_EVENTO_CTRL" 
   (	"ID_EVENTO" NUMBER NOT NULL ENABLE, 
	"CODBARRAETQ" VARCHAR2(80) NOT NULL ENABLE, 
	"ORIGEM" VARCHAR2(20) NOT NULL ENABLE, 
	"STATUS_ORIGEM" VARCHAR2(40), 
	"NROCARGA" NUMBER, 
	"NROEMPRESA" NUMBER, 
	"SEQPALETECARREG" NUMBER, 
	"FKMISSAO" NUMBER, 
	"FKVOLUME" NUMBER, 
	"REJEITADO" NUMBER(1,0), 
	"DESVIADO" NUMBER(1,0), 
	"DTA_EVENTO_ORIGEM" DATE, 
	"DTA_CAPTURA" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"HASH_EVENTO" VARCHAR2(100), 
	"OBS" VARCHAR2(4000), 
	 CONSTRAINT "PK_DD_SORTER_EVENTO_CTRL" PRIMARY KEY ("ID_EVENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSD_CONSINCO"  ENABLE
   ))
  TABLESPACE "TSD_CONSINCO"
