-- =============================================================================
-- INDEX: IX_DD_SORTER_BATCH_CARGA_ST
-- Exportado de CD2@2026-07-01 (fonte: banco remoto)
-- =============================================================================

CREATE INDEX "CD2"."IX_DD_SORTER_BATCH_CARGA_ST" ON "CD2"."DD_SORTER_BATCH_CARGA_CTRL" ("STATUS", "PRIORIDADE" DESC, "NROCARGA" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSD_CONSINCO"
