-- =============================================================================
-- TABLE: DD_SORTER_VINCULO_RETORNO_ETQ
-- Exportado de CD2@2026-07-06 (fonte: banco remoto)
-- =============================================================================

CREATE TABLE "CD2"."DD_SORTER_VINCULO_RETORNO_ETQ" 
   (	"ID_VINCULO" NUMBER NOT NULL ENABLE, 
	"CODBARRAETQ" VARCHAR2(80) NOT NULL ENABLE, 
	"ID_GPT_RETORNO" NUMBER NOT NULL ENABLE, 
	"NROCARGA" NUMBER, 
	"NROEMPRESA" NUMBER, 
	"SEQPRODUTO" NUMBER, 
	"SEQPALETECARREG" NUMBER, 
	"PALLET_INVENT" VARCHAR2(50), 
	"DTA_VINCULO" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_DD_SORTER_VINCULO_RET" PRIMARY KEY ("ID_VINCULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSD_CONSINCO"  ENABLE, 
	 CONSTRAINT "UK_DD_SORTER_VINCULO_ETQ" UNIQUE ("CODBARRAETQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSD_CONSINCO"  ENABLE, 
	 CONSTRAINT "UK_DD_SORTER_VINCULO_RET" UNIQUE ("ID_GPT_RETORNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSD_CONSINCO"  ENABLE
   ))
  TABLESPACE "TSD_CONSINCO"
