-- =============================================================================
-- VIEW: DDV_SORTER_CORRELACAO_ENRIQ
-- Exportado de CD2@2026-07-06 (fonte: banco remoto)
-- =============================================================================

CREATE OR REPLACE VIEW CD2."DDV_SORTER_CORRELACAO_ENRIQ" AS
SELECT
  e.CODBARRAETQ,
  e.NROCARGA,
  e.NROEMPRESA,
  NVL(e.EMPRESA_NOME, 'EMPRESA_' || TO_CHAR(e.NROEMPRESA)) AS EMPRESA_NOME,
  e.TIPOCARGA,
  e.TIPESPECIE,
  e.SEQPRODUTO,
  NVL(e.PRODUTO_DESC_REDUZIDA, 'PRODUTO_' || TO_CHAR(e.SEQPRODUTO)) AS PRODUTO_DESC_REDUZIDA,
  NVL(e.CODACESSO_PRINCIPAL, 'SEM_COD_' || TO_CHAR(e.SEQPRODUTO)) AS CODACESSO_PRINCIPAL,
  NVL(
    CASE
      WHEN INSTR(TRIM(e.DESC_TIPESPECIE), '-') > 0
      THEN SUBSTR(TRIM(e.DESC_TIPESPECIE), 1, INSTR(TRIM(e.DESC_TIPESPECIE), '-') - 1)
	   || ' - '
	   || SUBSTR(TRIM(e.DESC_TIPESPECIE), INSTR(TRIM(e.DESC_TIPESPECIE), '-') + 1)
    END,
    NVL(
      CASE
	WHEN e.DESTINO_CARGA IS NOT NULL
	 AND UPPER(TRIM(e.DESTINO_CARGA)) NOT LIKE 'PICKING SORTER%'
	THEN e.DESTINO_CARGA
      END,
      'CARGA_' || TO_CHAR(e.NROCARGA)
    )
  ) AS DESTINO_CARGA,
  e.STATUS_CARGA_EXPED,
  e.NROCARGA_RECEB_ORIGEM,
  e.IND_SORTER_PALETE_INTEIRO,
  e.IND_SORTER_PICKING,
  e.SEQFAMILIA,
  e.QTD_EMB_SOLICITADA,
  e.QTD_EMB_SEPARADA,
  e.QTD_EMB_CANCELADA,
  e.QTD_EMB_FATOR,
  e.EMBALAGEM_DESC,
  e.PESO_BRUTO_EMB,
  e.PESO_LIQUIDO_EMB,
  e.ALTURA_EMB,
  e.LARGURA_EMB,
  e.COMPRIMENTO_EMB,
  e.IND_ESTEIRA_SORTER,
  e.IND_VALIDA_MONTAGEM_PALETE,
  e.CODLINHASEPAR,
  e.DESC_LINHASEPAR,
  e.IND_SEPARACAO_LINHA,
  e.DESC_TIPESPECIE,
  e.QTD_PALETES_CARGA,
  e.QTD_VOLUMES_CARGA,
  e.QTD_ITENS_CARGA,
  e.PESO_TOTAL_CARGA,
  e.MCUB_TOTAL_CARGA,
  e.QTD_PALETES_PROD,
  e.QTD_TOTAL_PROD_PALETE,
  e.PESO_BRUTO_TOTAL_PROD,
  e.PESO_LIQUIDO_TOTAL_PROD,
  e.STATUS_CARGA_RECEB,
  e.STATUS_ARMAZENAGEM_RECEB,
  e.INDPROCESSADO			    AS C5_PROC_ENVIO,
  r.INDPROCESSADO			    AS C5_PROC_RETORNO,
  r.CODPRODUTIVO,
  NVL(r.PRODUTIVO_NOME, 'PROD_' || TO_CHAR(r.CODPRODUTIVO)) AS PRODUTIVO_NOME,
  i.STATUS_VOLUME,
  i.STATUS_SORTER,
  i.REJEITADO,
  i.DESVIADO,
  i.TIMELEITURA,
  i.TIMEACKN
FROM CD2.DDV_SORTER_FILA_ENVIO_ENRIQ e
LEFT JOIN CD2.DDV_SORTER_RETORNO_C5_ENRIQ r
  ON r.CODBARRAETQ = e.CODBARRAETQ
LEFT JOIN CD2.DDV_SORTER_STATUS_INVENT i
  ON i.CODBARRAETQ = e.CODBARRAETQ
