-- =============================================================================
-- VIEW: DDV_SORTER_FILA_ENVIO_ENRIQ
-- CODACESSO_PRINCIPAL: DUN (MAP TIPCODIGO D) na QTDEMBALAGEM da carga/palete;
--   se ausente, fallback EAN (TIPCODIGO E) na mesma embalagem.
-- Alt 2026-07-20: multiplos DUN/EAN na mesma embalagem → LISTAGG separados por virgula
--   (Invent/Velox aceita N codigos; indução casa o codigo fisico correto).
--   Cap: SUBSTR 1000 (= GPT_INTEGRA_REMESSA.CODACESSO / V_CODACESSO na 034).
-- =============================================================================

CREATE OR REPLACE VIEW CD2."DDV_SORTER_FILA_ENVIO_ENRIQ" AS
SELECT
i.CODBARRAETQ,
i.NROCARGA,
i.NROEMPRESA,
i.TIPOCARGA,
i.SEQPRODUTO,
i.TIPESPECIE,
i.INDPROCESSADO,
i.INDOPERACAO,
i.DTAHORALTERACAO,
ce.DESTINO				  AS DESTINO_CARGA,
ce.STATUSCARGA			  AS STATUS_CARGA_EXPED,
ce.NROCARGARECEB			  AS NROCARGA_RECEB_ORIGEM,
ce.INDSORTERPALETEINTEIRO		  AS IND_SORTER_PALETE_INTEIRO,
ce.INDSORTERPICKING			  AS IND_SORTER_PICKING,
emp.NOMEREDUZIDO			  AS EMPRESA_NOME,
emp.RAZAOSOCIAL			  AS EMPRESA_RAZAO,
p.DESCCOMPLETA			  AS PRODUTO_DESC_COMPLETA,
p.DESCREDUZIDA			  AS PRODUTO_DESC_REDUZIDA,
p.SEQFAMILIA				  AS SEQFAMILIA,
COALESCE(pc_d.CODACESSO_PRINCIPAL, pc_e.CODACESSO_PRINCIPAL) AS CODACESSO_PRINCIPAL,
cp.QTDEMBSOLICITADA			  AS QTD_EMB_SOLICITADA,
cp.QTDEMBSEPARADA			  AS QTD_EMB_SEPARADA,
cp.QTDEMBCANCELADA			  AS QTD_EMB_CANCELADA,
NVL(cp.QTDEMBALAGEM, pe.QTDEMBALAGEM)   AS QTD_EMB_FATOR,
fe.EMBALAGEM				  AS EMBALAGEM_DESC,
fe.PESOBRUTO				  AS PESO_BRUTO_EMB,
fe.PESOLIQUIDO			  AS PESO_LIQUIDO_EMB,
fe.ALTURA				  AS ALTURA_EMB,
fe.LARGURA				  AS LARGURA_EMB,
fe.PROFUNDIDADE			  AS COMPRIMENTO_EMB,
wm.INDESTEIRASORTER			  AS IND_ESTEIRA_SORTER,
wm.INDEXGVALIDACAOMONTAGEMPALETE	  AS IND_VALIDA_MONTAGEM_PALETE,
pw.CODLINHASEPAR			  AS CODLINHASEPAR,
ls.DESCLINHASEPAR			  AS DESC_LINHASEPAR,
ls.INDSEPARACAO			  AS IND_SEPARACAO_LINHA,
ts.DESCTIPESPECIE			  AS DESC_TIPESPECIE,
cap.QTD_PALETES_CARGA 		  AS QTD_PALETES_CARGA,
cap.QTD_VOLUMES_CARGA 		  AS QTD_VOLUMES_CARGA,
cap.QTD_ITENS_CARGA			  AS QTD_ITENS_CARGA,
cap.PESO_TOTAL_CARGA			  AS PESO_TOTAL_CARGA,
cap.MCUB_TOTAL_CARGA			  AS MCUB_TOTAL_CARGA,
prx.QTD_PALETES_PROD			  AS QTD_PALETES_PROD,
prx.QTD_TOTAL_PROD_PALETE		  AS QTD_TOTAL_PROD_PALETE,
prx.PESO_BRUTO_TOTAL_PROD		  AS PESO_BRUTO_TOTAL_PROD,
prx.PESO_LIQUIDO_TOTAL_PROD		  AS PESO_LIQUIDO_TOTAL_PROD,
cr.STATUSCARGA			  AS STATUS_CARGA_RECEB,
cr.STATUSARMAZENAGEM			  AS STATUS_ARMAZENAGEM_RECEB
FROM CONSINCO.MLO_INTEGRACAOSORTER i
LEFT JOIN CONSINCO.MLO_CARGAEXPED ce
ON ce.NROCARGA = i.NROCARGA
 AND ce.NROEMPRESA = i.NROEMPRESA
LEFT JOIN CONSINCO.MAX_EMPRESA emp
ON emp.NROEMPRESA = i.NROEMPRESA
LEFT JOIN CONSINCO.MAP_PRODUTO p
ON p.SEQPRODUTO = i.SEQPRODUTO
LEFT JOIN (
SELECT
  x.NROCARGA,
  x.NROEMPRESA,
  x.SEQPRODUTO,
  MAX(x.QTDEMBSOLICITADA) AS QTDEMBSOLICITADA,
  MAX(x.QTDEMBSEPARADA)   AS QTDEMBSEPARADA,
  MAX(x.QTDEMBCANCELADA)  AS QTDEMBCANCELADA,
  MAX(x.QTDEMBALAGEM)     AS QTDEMBALAGEM
FROM CONSINCO.MLO_CARGAEPRODUTO x
GROUP BY x.NROCARGA, x.NROEMPRESA, x.SEQPRODUTO
) cp
ON cp.NROCARGA = i.NROCARGA
 AND cp.NROEMPRESA = i.NROEMPRESA
 AND cp.SEQPRODUTO = i.SEQPRODUTO
LEFT JOIN (
SELECT
  x.NROEMPRESA,
  NVL(x.NROCARGAJUNCAO, x.NROCARGARECEB) AS NROCARGA_REF,
  x.SEQPRODUTO,
  x.TIPESPECIE,
  MAX(x.QTDEMBALAGEM) AS QTDEMBALAGEM
FROM CONSINCO.MLO_PALETE x
GROUP BY
  x.NROEMPRESA,
  NVL(x.NROCARGAJUNCAO, x.NROCARGARECEB),
  x.SEQPRODUTO,
  x.TIPESPECIE
) pe
ON pe.NROEMPRESA = i.NROEMPRESA
 AND pe.NROCARGA_REF = i.NROCARGA
 AND pe.SEQPRODUTO = i.SEQPRODUTO
 AND pe.TIPESPECIE = i.TIPESPECIE
LEFT JOIN (
SELECT
  x.SEQPRODUTO,
  x.QTDEMBALAGEM,
  SUBSTR(
    LISTAGG(x.CODACESSO, ',') WITHIN GROUP (ORDER BY x.CODACESSO),
    1,
    1000
  ) AS CODACESSO_PRINCIPAL
FROM CONSINCO.MAP_PRODCODIGO x
WHERE x.TIPCODIGO = 'D'
GROUP BY x.SEQPRODUTO, x.QTDEMBALAGEM
) pc_d
ON pc_d.SEQPRODUTO = i.SEQPRODUTO
 AND pc_d.QTDEMBALAGEM = NVL(cp.QTDEMBALAGEM, pe.QTDEMBALAGEM)
LEFT JOIN (
SELECT
  x.SEQPRODUTO,
  x.QTDEMBALAGEM,
  SUBSTR(
    LISTAGG(x.CODACESSO, ',') WITHIN GROUP (ORDER BY x.CODACESSO),
    1,
    1000
  ) AS CODACESSO_PRINCIPAL
FROM CONSINCO.MAP_PRODCODIGO x
WHERE x.TIPCODIGO = 'E'
GROUP BY x.SEQPRODUTO, x.QTDEMBALAGEM
) pc_e
ON pc_e.SEQPRODUTO = i.SEQPRODUTO
 AND pc_e.QTDEMBALAGEM = NVL(cp.QTDEMBALAGEM, pe.QTDEMBALAGEM)
LEFT JOIN CONSINCO.MAP_FAMEMBALAGEM fe
ON fe.SEQFAMILIA = p.SEQFAMILIA
 AND fe.QTDEMBALAGEM = NVL(cp.QTDEMBALAGEM, pe.QTDEMBALAGEM)
LEFT JOIN CONSINCO.MRL_PRODEMPRESAWM wm
ON wm.SEQPRODUTO = i.SEQPRODUTO
 AND wm.NROEMPRESA = i.NROEMPRESA
LEFT JOIN (
/* Linha operacional: MLO_PRODEMBWM traz varias linhas por embalagem (AV avaria, SN/SO Sorter, etc.).
   MIN() alfabeticamente favorecia AV e classificava errado. Priorizar linhas Sorter/operacionais e AV por ultimo. */
SELECT
  x.SEQPRODUTO,
  x.NROEMPRESA,
  x.QTDEMBALAGEM,
  MAX(x.CODLINHASEPAR) KEEP (
    DENSE_RANK FIRST ORDER BY
      CASE WHEN UPPER(TRIM(x.CODLINHASEPAR)) = 'AV' THEN 1 ELSE 0 END,
      CASE
        WHEN UPPER(TRIM(x.CODLINHASEPAR)) IN ('SA', 'SN', 'SO', 'SP', 'SE', 'SS') THEN 0
        ELSE 1
      END,
      x.CODLINHASEPAR
  ) AS CODLINHASEPAR
FROM CONSINCO.MLO_PRODEMBWM x
GROUP BY x.SEQPRODUTO, x.NROEMPRESA, x.QTDEMBALAGEM
) pw
ON pw.SEQPRODUTO = i.SEQPRODUTO
 AND pw.NROEMPRESA = i.NROEMPRESA
 AND pw.QTDEMBALAGEM = NVL(cp.QTDEMBALAGEM, pe.QTDEMBALAGEM)
LEFT JOIN CONSINCO.MLO_LINHASEPARACAO ls
ON ls.CODLINHASEPAR = pw.CODLINHASEPAR
 AND ls.NROEMPRESA = i.NROEMPRESA
LEFT JOIN CONSINCO.MLO_TIPESPECIE ts
ON ts.TIPESPECIE = i.TIPESPECIE
 AND ts.NROEMPRESA = i.NROEMPRESA
LEFT JOIN (
SELECT
  x.NROCARGA,
  x.NROEMPRESA,
  COUNT(*)		  AS QTD_PALETES_CARGA,
  SUM(x.QTDVOLUME)	  AS QTD_VOLUMES_CARGA,
  SUM(x.QTDITEM)	  AS QTD_ITENS_CARGA,
  SUM(x.PESOTOTALLOTE)  AS PESO_TOTAL_CARGA,
  SUM(x.MCUBTOTALLOTE)  AS MCUB_TOTAL_CARGA
FROM CONSINCO.MLO_CARGAEPALETE x
GROUP BY x.NROCARGA, x.NROEMPRESA
) cap
ON cap.NROCARGA = i.NROCARGA
 AND cap.NROEMPRESA = i.NROEMPRESA
LEFT JOIN (
SELECT
  x.NROEMPRESA,
  NVL(x.NROCARGAJUNCAO, x.NROCARGARECEB) AS NROCARGA_REF,
  x.SEQPRODUTO,
  x.TIPESPECIE,
  COUNT(*)		  AS QTD_PALETES_PROD,
  SUM(x.QTDEMBALAGEM)   AS QTD_TOTAL_PROD_PALETE,
  SUM(x.PESOBRUTO)	  AS PESO_BRUTO_TOTAL_PROD,
  SUM(x.PESOLIQUIDO)	  AS PESO_LIQUIDO_TOTAL_PROD
FROM CONSINCO.MLO_PALETE x
WHERE x.TIPOCARGA = 'E'
GROUP BY
  x.NROEMPRESA,
  NVL(x.NROCARGAJUNCAO, x.NROCARGARECEB),
  x.SEQPRODUTO,
  x.TIPESPECIE
) prx
ON prx.NROEMPRESA = i.NROEMPRESA
 AND prx.NROCARGA_REF = i.NROCARGA
 AND prx.SEQPRODUTO = i.SEQPRODUTO
 AND prx.TIPESPECIE = i.TIPESPECIE
LEFT JOIN CONSINCO.MLO_CARGARECEB cr
ON cr.NROCARGA = i.NROCARGA
 AND cr.NROEMPRESA = i.NROEMPRESA
