-- =============================================================================
-- VIEW: DDV_SORTER_KPI_DIARIO_HML
-- Exportado de CD2@2026-07-06 (fonte: banco remoto)
-- =============================================================================

CREATE OR REPLACE VIEW CD2."DDV_SORTER_KPI_DIARIO_HML" AS
SELECT
  TRUNC(DTA_CAPTURA) AS DIA,
  COUNT(*) AS EVT_TOTAL,
  SUM(CASE WHEN ORIGEM = 'INVENT' THEN 1 ELSE 0 END) AS EVT_INVENT,
  SUM(CASE WHEN ORIGEM = 'RECON' THEN 1 ELSE 0 END) AS EVT_RECON,
  SUM(CASE WHEN ORIGEM = 'FECHAMENTO' THEN 1 ELSE 0 END) AS EVT_FECHAMENTO,
  SUM(CASE WHEN STATUS_ORIGEM = 'C5_FECHADO' THEN 1 ELSE 0 END) AS C5_FECHADO,
  SUM(CASE WHEN STATUS_ORIGEM = 'C5_JA_FECHADO' THEN 1 ELSE 0 END) AS C5_JA_FECHADO,
  SUM(CASE WHEN STATUS_ORIGEM = 'NAO_FECHADO' THEN 1 ELSE 0 END) AS NAO_FECHADO,
  SUM(CASE WHEN STATUS_ORIGEM = 'ERRO' THEN 1 ELSE 0 END) AS ERROS
FROM CD2.DD_SORTER_EVENTO_CTRL
GROUP BY TRUNC(DTA_CAPTURA)
