-- =============================================================================
-- VIEW: DDV_SORTER_PENDENCIAS
-- Exportado de CD2@2026-07-06 (fonte: banco remoto)
-- =============================================================================

CREATE OR REPLACE VIEW CD2."DDV_SORTER_PENDENCIAS" AS
SELECT
  c.CODBARRAETQ,
  c.NROCARGA,
  c.NROEMPRESA,
  c.TIPOCARGA,
  c.C5_PROC,
  c.STATUS_VOLUME,
  c.STATUS_SORTER,
  c.REJEITADO,
  c.DESVIADO,
  CASE
    WHEN c.CODBARRAETQ IS NULL THEN 'ERRO_CHAVE'
    WHEN EXISTS (
	   SELECT 1
	     FROM CD2.DD_SORTER_EVENTO_CTRL ev
	    WHERE ev.CODBARRAETQ = c.CODBARRAETQ
	      AND ev.ORIGEM = 'ENVIO'
	      AND ev.STATUS_ORIGEM = 'BLOQUEIO_SEM_CODACESSO'
	 )
      OR EXISTS (
	   SELECT 1
	     FROM CD2.DDV_SORTER_CORRELACAO_ENRIQ e
	    WHERE e.CODBARRAETQ = c.CODBARRAETQ
	      AND e.CODACESSO_PRINCIPAL LIKE 'SEM_COD_%'
	 ) THEN 'PENDENTE_CODACESSO_MAP'
    WHEN c.STATUS_VOLUME IS NULL AND c.STATUS_SORTER IS NULL THEN 'NAO_ENVIADO_INVENT'
    WHEN c.STATUS_SORTER = 'INDUZIDO' AND NVL(c.C5_PROC,'N') <> 'S' THEN 'RETORNO_PENDENTE_C5'
    WHEN c.STATUS_SORTER IN ('REJEITADO','DESVIADO','CANCELADO') THEN 'TRATAR_EXCECAO'
    ELSE 'OK'
  END AS STATUS_CONCILIACAO
FROM CD2.DDV_SORTER_CORRELACAO c
