-- =============================================================================
-- VIEW: DDV_SORTER_STATUS_INVENT
-- Exportado de CD2@2026-07-06 (fonte: banco remoto)
-- =============================================================================

CREATE OR REPLACE VIEW CD2."DDV_SORTER_STATUS_INVENT" AS
SELECT
  c.CODBARRAETQ,
  CAST(NULL AS NUMBER)		AS FKMISSAO,
  CAST(NULL AS NUMBER)		AS FKVOLUME,
  NVL(g.STATUS, 'PENDENTE')	AS STATUS_VOLUME,
  CASE
    WHEN k.DATA_CANCELAMENTO IS NOT NULL THEN 'CANCELADO'
    WHEN EXISTS (
	   SELECT 1
	     FROM CD2.DD_SORTER_VINCULO_RETORNO_ETQ v
	    WHERE v.CODBARRAETQ = c.CODBARRAETQ
	 ) THEN 'INDUZIDO'
    WHEN EXISTS (
	   SELECT 1
	     FROM CONSINCO.MLO_MONTAGEMSORTER m
	    WHERE m.CODBARRAETQ = c.CODBARRAETQ
	      AND m.SEQPALETECARREG IS NOT NULL
	 ) THEN 'INDUZIDO'
    WHEN EXISTS (
	   SELECT 1
	     FROM CONSINCO.MLO_PALCARREGRF prf
	     JOIN CONSINCO.MLO_PALETE p
	       ON p.SEQPALETERF = prf.SEQPALETERF
	    WHERE p.NROCARGARECEB = c.NROCARGA
	      AND p.NROEMPRESA = c.NROEMPRESA
	      AND p.SEQPRODUTO = c.SEQPRODUTO
	      AND p.TIPESPECIE = c.TIPESPECIE
	      AND prf.SEQPALETECARREG IS NOT NULL
	      AND prf.SEQPALETEQTDE = CASE
		    WHEN REGEXP_LIKE(c.CODBARRAETQ, '([0-9]{7}|[0-9]{6})$')
		      THEN TO_NUMBER(REGEXP_SUBSTR(c.CODBARRAETQ, '([0-9]{7}|[0-9]{6})$'))
		    ELSE NULL
		  END
	 ) THEN 'INDUZIDO'
    WHEN EXISTS (
	   SELECT 1
	     FROM "GPT_RETORNO_MONTAGEM_PALETES"@INVENT r2
	     JOIN CONSINCO.MLO_TIPESPECIE ts
	       ON ts.NROEMPRESA = c.NROEMPRESA
	      AND ts.TIPESPECIE = c.TIPESPECIE
	    WHERE r2.EMPRESA = c.NROEMPRESA
	      AND r2.ONDA = c.NROCARGA
	      AND r2.SEQPRODUTO = c.SEQPRODUTO
	      AND r2.DATA_FECHAMENTO IS NOT NULL
	      AND (
		    (r2.LOJA <> r2.EMPRESA
		     AND r2.LOJA = TO_NUMBER(REGEXP_SUBSTR(TRIM(ts.DESCTIPESPECIE), '^[0-9]+')))
		 OR EXISTS (
		       SELECT 1
			 FROM CD2.DD_SORTER_VINCULO_RETORNO_ETQ v3
			 JOIN CONSINCO.MLO_INTEGRACAOSORTER i3
			   ON i3.CODBARRAETQ = v3.CODBARRAETQ
			WHERE v3.NROCARGA = c.NROCARGA
			  AND v3.PALLET_INVENT = r2.PALLET
			  AND i3.TIPESPECIE = c.TIPESPECIE
		   )
		  )
	      AND NOT EXISTS (
		    SELECT 1
		      FROM CD2.DD_SORTER_VINCULO_RETORNO_ETQ v2
		     WHERE v2.ID_GPT_RETORNO = r2.ID_GPT_RETORNO_MONTAGEM_PALETES
		 )
	 ) THEN 'RETORNO_PRODUTO'
    WHEN r.QUANTIDADE = 0 THEN 'CANCELADO'
    WHEN g.DATA_RECEBIMENTO IS NOT NULL THEN 'RECEBIDO'
    ELSE NULL
  END				AS STATUS_SORTER,
  CASE
    WHEN k.DATA_CANCELAMENTO IS NOT NULL THEN 1
    WHEN r.QUANTIDADE = 0 THEN 1
    ELSE 0
  END				AS REJEITADO,
  CAST(0 AS NUMBER)		AS DESVIADO,
  g.DATA_RECEBIMENTO		AS TIMELEITURA,
  NVL(k.DATA_CANCELAMENTO, r.DATA_ENVIO) AS TIMEACKN
FROM CD2.DDV_SORTER_FILA_ENVIO_ENRIQ c
LEFT JOIN CONSINCO.MLO_INTEGRACAOSORTER i_env
  ON i_env.CODBARRAETQ = c.CODBARRAETQ
LEFT JOIN CONSINCO.MLO_TIPESPECIE tsk
  ON tsk.NROEMPRESA = c.NROEMPRESA
 AND tsk.TIPESPECIE = c.TIPESPECIE
LEFT JOIN (
  SELECT ev.CODBARRAETQ,
	 MAX(
	   TO_NUMBER(
	     SUBSTR(
	       ev.OBS,
	       INSTR(ev.OBS, 'SEQLOTE=') + 8,
	       CASE
		 WHEN INSTR(ev.OBS, ' ', INSTR(ev.OBS, 'SEQLOTE=') + 8) > 0
		   THEN INSTR(ev.OBS, ' ', INSTR(ev.OBS, 'SEQLOTE=') + 8) - INSTR(ev.OBS, 'SEQLOTE=') - 8
		 ELSE 20
	       END
	     )
	   )
	 ) AS SEQLOTE_ENV
    FROM CD2.DD_SORTER_EVENTO_CTRL ev
   WHERE ev.ORIGEM = 'ENVIO'
     AND ev.STATUS_ORIGEM = 'ENVIADO_INVENT'
     AND ev.OBS LIKE 'ENVIO INTEGRACAO TOTAL DESTINO%'
     AND INSTR(ev.OBS, 'SEQLOTE=') > 0
   GROUP BY ev.CODBARRAETQ
) ev_seq
  ON ev_seq.CODBARRAETQ = c.CODBARRAETQ
LEFT JOIN "GPT_INTEGRA_REMESSA"@INVENT g
  ON g.EMPRESA = c.NROEMPRESA
 AND g.ONDA = c.NROCARGA
 AND g.SEQPRODUTO = c.SEQPRODUTO
 AND g.LOJA = CASE
       WHEN REGEXP_LIKE(TRIM(tsk.DESCTIPESPECIE), '^[0-9]+')
	 THEN TO_NUMBER(REGEXP_SUBSTR(TRIM(tsk.DESCTIPESPECIE), '^[0-9]+'))
       WHEN REGEXP_LIKE(TRIM(c.TIPESPECIE), '^[0-9]+$')
	 THEN 1000 + TO_NUMBER(TRIM(c.TIPESPECIE))
       ELSE c.NROEMPRESA
     END
 AND g.SEQLOTE = NVL(
       ev_seq.SEQLOTE_ENV,
       CASE
	 WHEN i_env.ETIQUETAORIGEM IS NOT NULL THEN i_env.ETIQUETAORIGEM
	 WHEN REGEXP_LIKE(TRIM(c.TIPESPECIE), '^[0-9]+$') THEN TO_NUMBER(TRIM(c.TIPESPECIE))
	 ELSE ABS(MOD(ORA_HASH(NVL(c.TIPESPECIE, c.CODBARRAETQ)), 999999))
       END
     )
LEFT JOIN (
  SELECT
    x.EMPRESA,
    x.ONDA,
    x.SEQPRODUTO,
    MAX(x.QUANTIDADE) KEEP (DENSE_RANK LAST ORDER BY x.DATA_ENVIO) AS QUANTIDADE,
    MAX(x.DATA_FECHAMENTO) KEEP (DENSE_RANK LAST ORDER BY x.DATA_ENVIO) AS DATA_FECHAMENTO,
    MAX(x.DATA_ENVIO) AS DATA_ENVIO
  FROM "GPT_RETORNO_MONTAGEM_PALETES"@INVENT x
  GROUP BY x.EMPRESA, x.ONDA, x.SEQPRODUTO
) r
  ON r.EMPRESA = c.NROEMPRESA
 AND r.ONDA = c.NROCARGA
 AND r.SEQPRODUTO = c.SEQPRODUTO
LEFT JOIN (
  SELECT
    x.EMPRESA,
    x.ONDA,
    x.SEQPRODUTO,
    x.LOJA,
    MAX(x.DATA_CANCELAMENTO) AS DATA_CANCELAMENTO
  FROM "GPT_CANCELAMENTO_REMESSAS"@INVENT x
  GROUP BY x.EMPRESA, x.ONDA, x.SEQPRODUTO, x.LOJA
) k
  ON k.EMPRESA = c.NROEMPRESA
 AND k.ONDA = c.NROCARGA
 AND k.SEQPRODUTO = c.SEQPRODUTO
 AND k.LOJA = CASE
       WHEN REGEXP_LIKE(TRIM(tsk.DESCTIPESPECIE), '^[0-9]+')
         THEN TO_NUMBER(REGEXP_SUBSTR(TRIM(tsk.DESCTIPESPECIE), '^[0-9]+'))
       ELSE NULL
     END
