-- =============================================================================
-- PACKAGE_BODY: DD_PKG_FECHA_CACHE
-- Exportado de CD2@2026-07-01 (fonte: banco remoto)
-- =============================================================================

CREATE OR REPLACE PACKAGE BODY DD_PKG_FECHA_CACHE AS
  TYPE T_NUM_MAP IS TABLE OF NUMBER INDEX BY VARCHAR2(200);
  G_QTD_PEND  T_NUM_MAP;
  G_CNT_PALLET T_NUM_MAP;

  PROCEDURE CLEAR_ALL IS
  BEGIN
    G_QTD_PEND.DELETE;
    G_CNT_PALLET.DELETE;
  END CLEAR_ALL;

  FUNCTION GET_QTD_PEND(P_KEY IN VARCHAR2, P_VAL OUT NUMBER) RETURN BOOLEAN IS
  BEGIN
    IF P_KEY IS NOT NULL AND G_QTD_PEND.EXISTS(P_KEY) THEN
      P_VAL := G_QTD_PEND(P_KEY);
      RETURN TRUE;
    END IF;
    RETURN FALSE;
  END GET_QTD_PEND;

  PROCEDURE SET_QTD_PEND(P_KEY IN VARCHAR2, P_VAL IN NUMBER) IS
  BEGIN
    IF P_KEY IS NOT NULL THEN
      G_QTD_PEND(P_KEY) := P_VAL;
    END IF;
  END SET_QTD_PEND;

  PROCEDURE DECR_QTD_PEND(P_KEY IN VARCHAR2) IS
  BEGIN
    IF P_KEY IS NOT NULL AND G_QTD_PEND.EXISTS(P_KEY) AND G_QTD_PEND(P_KEY) > 0 THEN
      G_QTD_PEND(P_KEY) := G_QTD_PEND(P_KEY) - 1;
    END IF;
  END DECR_QTD_PEND;

  FUNCTION GET_CNT_PALLET(P_KEY IN VARCHAR2, P_VAL OUT NUMBER) RETURN BOOLEAN IS
  BEGIN
    IF P_KEY IS NOT NULL AND G_CNT_PALLET.EXISTS(P_KEY) THEN
      P_VAL := G_CNT_PALLET(P_KEY);
      RETURN TRUE;
    END IF;
    RETURN FALSE;
  END GET_CNT_PALLET;

  PROCEDURE SET_CNT_PALLET(P_KEY IN VARCHAR2, P_VAL IN NUMBER) IS
  BEGIN
    IF P_KEY IS NOT NULL THEN
      G_CNT_PALLET(P_KEY) := P_VAL;
    END IF;
  END SET_CNT_PALLET;
END DD_PKG_FECHA_CACHE;
