-- =============================================================================
-- PROCEDURE: DD_PRC_CAPTURA_STATUS_INVENT
-- Exportado de CD2@2026-07-01 (fonte: banco remoto)
-- =============================================================================

CREATE OR REPLACE PROCEDURE "DD_PRC_CAPTURA_STATUS_INVENT" (
  P_CODBARRAETQ IN VARCHAR2 DEFAULT NULL,
  P_LIMIT	IN NUMBER   DEFAULT 500
) AS
BEGIN
  BEGIN
    INSERT INTO CD2.DD_SORTER_EVENTO_CTRL (
      ID_EVENTO,
      CODBARRAETQ,
      ORIGEM,
      STATUS_ORIGEM,
      NROCARGA,
      NROEMPRESA,
      FKMISSAO,
      FKVOLUME,
      REJEITADO,
      DESVIADO,
      DTA_EVENTO_ORIGEM,
      HASH_EVENTO,
      OBS
    )
    SELECT
      CD2.SQ_DD_SORTER_EVENTO_CTRL.NEXTVAL,
      c.CODBARRAETQ,
      'INVENT',
      NVL(c.STATUS_SORTER, c.STATUS_VOLUME),
      c.NROCARGA,
      c.NROEMPRESA,
      c.FKMISSAO,
      c.FKVOLUME,
      c.REJEITADO,
      c.DESVIADO,
      NVL(c.TIMEACKN, c.TIMELEITURA),
      c.CODBARRAETQ || '|' || NVL(c.STATUS_SORTER, c.STATUS_VOLUME) || '|' || TO_CHAR(NVL(c.TIMEACKN, c.TIMELEITURA), 'YYYYMMDDHH24MISS'),
      'CAPTURA DD AUTOMATICA'
    FROM (
      SELECT
	x.CODBARRAETQ,
	x.NROCARGA,
	x.NROEMPRESA,
	x.STATUS_VOLUME,
	x.STATUS_SORTER,
	x.REJEITADO,
	x.DESVIADO,
	x.FKMISSAO,
	x.FKVOLUME,
	x.TIMELEITURA,
	x.TIMEACKN
      FROM CD2.DDV_SORTER_CORRELACAO x
      WHERE P_CODBARRAETQ IS NULL OR x.CODBARRAETQ = P_CODBARRAETQ
      ORDER BY x.CODBARRAETQ
    ) c
    WHERE ROWNUM <= P_LIMIT
      AND NOT EXISTS (
	    SELECT 1
	      FROM CD2.DD_SORTER_EVENTO_CTRL t
	     WHERE t.HASH_EVENTO = c.CODBARRAETQ || '|' || NVL(c.STATUS_SORTER, c.STATUS_VOLUME) || '|' || TO_CHAR(NVL(c.TIMEACKN, c.TIMELEITURA), 'YYYYMMDDHH24MISS')
	  );
    COMMIT;
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      NULL;
  END;
END;
