-- =============================================================================
-- PROCEDURE: DD_PRC_RECONCILIA_ETIQUETA
-- Exportado de CD2@2026-07-06 (fonte: banco remoto)
-- =============================================================================

CREATE OR REPLACE PROCEDURE       "DD_PRC_RECONCILIA_ETIQUETA" (
  P_CODBARRAETQ IN VARCHAR2
) AS
  V_STATUS VARCHAR2(40);
  V_CARGA  NUMBER;
  V_EMP    NUMBER;
BEGIN
  SELECT
    STATUS_CONCILIACAO,
    NROCARGA,
    NROEMPRESA
  INTO
    V_STATUS,
    V_CARGA,
    V_EMP
  FROM CD2.DDV_SORTER_PENDENCIAS
  WHERE CODBARRAETQ = P_CODBARRAETQ
    AND ROWNUM = 1;

  INSERT INTO CD2.DD_SORTER_EVENTO_CTRL (
    ID_EVENTO,
    CODBARRAETQ,
    ORIGEM,
    STATUS_ORIGEM,
    NROCARGA,
    NROEMPRESA,
    DTA_EVENTO_ORIGEM,
    DTA_CAPTURA,
    HASH_EVENTO,
    OBS
  )
  VALUES (
    CD2.SQ_DD_SORTER_EVENTO_CTRL.NEXTVAL,
    P_CODBARRAETQ,
    'RECON',
    V_STATUS,
    V_CARGA,
    V_EMP,
    SYSDATE,
    SYSDATE,
    P_CODBARRAETQ || '|RECON|' || V_STATUS || '|' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
    'RECONCILIACAO MANUAL'
  );

  COMMIT;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO CD2.DD_SORTER_EVENTO_CTRL (
      ID_EVENTO, CODBARRAETQ, ORIGEM, STATUS_ORIGEM, DTA_EVENTO_ORIGEM, DTA_CAPTURA, HASH_EVENTO, OBS
    ) VALUES (
      CD2.SQ_DD_SORTER_EVENTO_CTRL.NEXTVAL,
      P_CODBARRAETQ,
      'RECON',
      'SEM_DADOS',
      SYSDATE,
      SYSDATE,
      P_CODBARRAETQ || '|RECON|SEM_DADOS|' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
      'ETIQUETA NAO ENCONTRADA NAS VIEWS DE CORRELACAO'
    );
    COMMIT;
END;
