-- =============================================================================
-- PROCEDURE: DD_PRC_ENVIA_C5_INVENT
-- Exportado de CD2@2026-07-06 (fonte: banco remoto)
-- =============================================================================

CREATE OR REPLACE PROCEDURE       "DD_PRC_ENVIA_C5_INVENT" (
  P_CODBARRAETQ IN VARCHAR2
) AS
  V_NROCARGA	 NUMBER;
  V_NROEMPRESA	 NUMBER;
  V_TIPOCARGA	 VARCHAR2(2);
  V_TIPESPECIE	 VARCHAR2(10);
  V_SEQPRODUTO	 NUMBER;
  V_CODACESSO	 VARCHAR2(1000);
  V_QTDEMB	 NUMBER;
  V_QTD_SEP_ETQ  NUMBER;
  V_DESC	 VARCHAR2(200);
  V_PESO	 NUMBER;
  V_ALTURA	 NUMBER;
  V_LARGURA	 NUMBER;
  V_COMP	 NUMBER;
  V_COD_PROD	 NUMBER;
  V_COD_RH	 VARCHAR2(30);
  V_PROD	 VARCHAR2(80);
  V_LOJA	 NUMBER;
  V_SEQLOTE	 NUMBER;
  V_ORDEM_SEPAR  NUMBER;
  V_ORDEM_SEPAR_TXT VARCHAR2(50);
  V_CODLINHASEPAR VARCHAR2(30);
  V_DESCLINHASEPAR VARCHAR2(200);
  V_ROTA	 VARCHAR2(80);
  V_CODRUA	 VARCHAR2(80) := NULL;
  V_TIPO_PRODUTO VARCHAR2(1);
  V_DESC_TIPO_PRODUTO VARCHAR2(40);
  V_ID_BASE	 NUMBER;
  V_EXISTE	 NUMBER := 0;
  V_JA_ENV_ETQ	 NUMBER;
  V_JA_BUF_ETQ	 NUMBER;
  V_QTD_PENDENTE NUMBER;
  V_QTD_PRONTA	 NUMBER;
  V_MIN_BUF_LEVA DATE;
  V_NUM_LEVAS_ENV NUMBER;
  V_LEVA_NUM	 NUMBER;
  V_QTD_GPT	 NUMBER;
  V_QTD_ATUAL	 NUMBER;
  V_STATUS_GPT	 VARCHAR2(40);
  V_TMP_COUNT	 NUMBER;
  V_ETIQUETA_ORIGEM NUMBER;
  V_ERR 	 VARCHAR2(3500);
  C_STATUS_GPT_ENV CONSTANT VARCHAR2(20) := 'PENDENTE';
  C_LEVA_JANELA_MIN CONSTANT NUMBER := 5;
  C_LEVA_MAX_VOLUMES CONSTANT NUMBER := 100;
  FUNCTION F_SANITIZA_INVENT(P_TXT IN VARCHAR2) RETURN VARCHAR2 IS
    V_SRC VARCHAR2(4000);
    V_OUT VARCHAR2(4000) := NULL;
    V_CH  VARCHAR2(1);
    V_I   PLS_INTEGER;
  BEGIN
    IF P_TXT IS NULL THEN
      RETURN NULL;
    END IF;
    V_SRC := TRANSLATE(P_TXT,
      '??????????????????????????????????????????????????????????????????????????????????????????????????????',
      'AAAAAEEEEIIIIOOOOOUUUUCNaaaaaeeeeiiiiooooouuuucnooa ');
    FOR V_I IN 1 .. LENGTH(V_SRC) LOOP
      V_CH := SUBSTR(V_SRC, V_I, 1);
      IF ASCII(V_CH) BETWEEN 32 AND 126 THEN
	V_OUT := V_OUT || V_CH;
      ELSIF ASCII(V_CH) IN (9, 10, 13) THEN
	V_OUT := V_OUT || ' ';
      END IF;
    END LOOP;
    RETURN TRIM(REGEXP_REPLACE(NVL(V_OUT, ''), ' +', ' '));
  END F_SANITIZA_INVENT;
  FUNCTION F_SEQLOTE_LEVA(
    P_ETIQ_ORIGEM IN NUMBER,
    P_LEVA_NUM    IN NUMBER,
    P_TIPESPECIE  IN VARCHAR2,
    P_CODBARRAETQ IN VARCHAR2
  ) RETURN NUMBER IS
  BEGIN
    IF P_LEVA_NUM <= 1 THEN
      IF P_ETIQ_ORIGEM IS NOT NULL THEN
	RETURN P_ETIQ_ORIGEM;
      ELSIF REGEXP_LIKE(TRIM(NVL(P_TIPESPECIE, '')), '^[0-9]+$') THEN
	RETURN TO_NUMBER(TRIM(P_TIPESPECIE));
      ELSE
	RETURN ABS(MOD(DBMS_UTILITY.GET_HASH_VALUE(NVL(P_TIPESPECIE, P_CODBARRAETQ), 1, 999999), 999999));
      END IF;
    END IF;
    IF P_ETIQ_ORIGEM IS NOT NULL THEN
      RETURN P_ETIQ_ORIGEM * 1000 + P_LEVA_NUM;
    ELSIF REGEXP_LIKE(TRIM(NVL(P_TIPESPECIE, '')), '^[0-9]+$') THEN
      RETURN TO_NUMBER(TRIM(P_TIPESPECIE)) * 1000 + P_LEVA_NUM;
    ELSE
      RETURN ABS(MOD(DBMS_UTILITY.GET_HASH_VALUE(NVL(P_TIPESPECIE, P_CODBARRAETQ), 1, 999999), 999999))
	     * 1000 + P_LEVA_NUM;
    END IF;
  END F_SEQLOTE_LEVA;
BEGIN
  SELECT
    c.NROCARGA,
    c.NROEMPRESA,
    c.TIPOCARGA,
    c.TIPESPECIE,
    c.SEQPRODUTO,
    c.CODACESSO_PRINCIPAL,
    c.QTD_EMB_FATOR,
    NVL(c.QTD_EMB_SEPARADA, 0),
    c.PRODUTO_DESC_REDUZIDA,
    c.PESO_BRUTO_EMB,
    c.ALTURA_EMB,
    c.LARGURA_EMB,
    c.COMPRIMENTO_EMB,
    c.CODPRODUTIVO,
    NULL,
    c.PRODUTIVO_NOME,
    c.DESTINO_CARGA,
    c.CODLINHASEPAR,
    c.CODLINHASEPAR,
    c.DESC_LINHASEPAR,
    NVL(
      (SELECT TO_NUMBER(REGEXP_SUBSTR(TRIM(t.DESCTIPESPECIE), '^[0-9]+'))
	 FROM CONSINCO.MLO_TIPESPECIE t
	WHERE t.NROEMPRESA = c.NROEMPRESA
	  AND t.TIPESPECIE = c.TIPESPECIE
	  AND REGEXP_LIKE(TRIM(t.DESCTIPESPECIE), '^[0-9]+')
	  AND ROWNUM = 1),
      CASE
	WHEN REGEXP_LIKE(TRIM(c.TIPESPECIE), '^[0-9]+$')
	  THEN 1000 + TO_NUMBER(TRIM(c.TIPESPECIE))
	ELSE c.NROEMPRESA
      END
    )
  INTO
    V_NROCARGA,
    V_NROEMPRESA,
    V_TIPOCARGA,
    V_TIPESPECIE,
    V_SEQPRODUTO,
    V_CODACESSO,
    V_QTDEMB,
    V_QTD_SEP_ETQ,
    V_DESC,
    V_PESO,
    V_ALTURA,
    V_LARGURA,
    V_COMP,
    V_COD_PROD,
    V_COD_RH,
    V_PROD,
    V_ROTA,
    V_ORDEM_SEPAR_TXT,
    V_CODLINHASEPAR,
    V_DESCLINHASEPAR,
    V_LOJA
  FROM CD2.DDV_SORTER_CORRELACAO_ENRIQ c
  WHERE c.CODBARRAETQ = P_CODBARRAETQ
    AND ROWNUM = 1;
  IF NVL(V_QTD_SEP_ETQ, 0) <= 0
     AND UPPER(TRIM(NVL(V_TIPOCARGA, 'E'))) <> 'R' THEN
    RETURN;
  END IF;
  BEGIN
    SELECT i.ETIQUETAORIGEM
      INTO V_ETIQUETA_ORIGEM
      FROM CONSINCO.MLO_INTEGRACAOSORTER i
     WHERE i.CODBARRAETQ = P_CODBARRAETQ
       AND ROWNUM = 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      V_ETIQUETA_ORIGEM := NULL;
  END;
  /* Sem CODACESSO valido (MAP x embalagem): nao envia remessa GPT / Velox. */
  V_CODACESSO := TRIM(V_CODACESSO);
  IF V_CODACESSO IS NULL
     OR UPPER(V_CODACESSO) LIKE 'SEM_COD_%' THEN
    SELECT COUNT(*)
      INTO V_TMP_COUNT
      FROM CD2.DD_SORTER_EVENTO_CTRL e
     WHERE e.CODBARRAETQ = P_CODBARRAETQ
       AND e.ORIGEM = 'ENVIO'
       AND e.STATUS_ORIGEM = 'BLOQUEIO_SEM_CODACESSO';
    IF V_TMP_COUNT = 0 THEN
      INSERT INTO CD2.DD_SORTER_EVENTO_CTRL (
	ID_EVENTO, CODBARRAETQ, ORIGEM, STATUS_ORIGEM, NROCARGA, NROEMPRESA,
	DTA_EVENTO_ORIGEM, DTA_CAPTURA, HASH_EVENTO, OBS
      ) VALUES (
	CD2.SQ_DD_SORTER_EVENTO_CTRL.NEXTVAL,
	P_CODBARRAETQ,
	'ENVIO',
	'BLOQUEIO_SEM_CODACESSO',
	V_NROCARGA,
	V_NROEMPRESA,
	SYSDATE,
	SYSDATE,
	P_CODBARRAETQ || '|ENVIO|BLOQUEIO|SEM_COD|' || TO_CHAR(V_SEQPRODUTO),
	'ENVIO INVENT BLOQUEADO: SEM CODACESSO MAP TIPO D PARA EMBALAGEM DA CARGA. PROD='
	  || TO_CHAR(V_SEQPRODUTO) || ' COD=' || NVL(V_CODACESSO, '(NULL)')
      );
      COMMIT;
    END IF;
    RETURN;
  END IF;
  SELECT COUNT(*)
    INTO V_JA_ENV_ETQ
    FROM CD2.DD_SORTER_EVENTO_CTRL e
   WHERE e.CODBARRAETQ = P_CODBARRAETQ
     AND e.ORIGEM = 'ENVIO'
     AND e.STATUS_ORIGEM IN ('ENVIADO_INVENT', 'ENVIO_AGG_INVENT');
  IF V_JA_ENV_ETQ > 0 THEN
    RETURN;
  END IF;
  SELECT COUNT(*)
    INTO V_JA_BUF_ETQ
    FROM CD2.DD_SORTER_EVENTO_CTRL e
   WHERE e.CODBARRAETQ = P_CODBARRAETQ
     AND e.ORIGEM = 'ENVIO'
     AND e.STATUS_ORIGEM = 'ENVIO_BUFFER';
  V_ORDEM_SEPAR := CASE
		     WHEN REGEXP_LIKE(NVL(V_ORDEM_SEPAR_TXT, ' '), '^[0-9]+$')
		       THEN TO_NUMBER(V_ORDEM_SEPAR_TXT)
		     ELSE NVL(V_SEQPRODUTO, V_NROCARGA)
		   END;
  IF V_ROTA IS NULL OR UPPER(TRIM(V_ROTA)) LIKE 'PICKING SORTER%' THEN
    V_ROTA := NULL;
  END IF;
  V_ROTA := SUBSTR(NVL(V_ROTA, 'LJ ' || LPAD(TO_CHAR(NVL(V_LOJA, 0)), 2, '0')), 1, 40);
  V_CODRUA := SUBSTR(LPAD(TO_CHAR(V_ORDEM_SEPAR), 3, '0'), 1, 3);
  /* Classificacao A/N: linhas Sorter contaminante (SA/SP) = N; nao contaminante (SN/SO) = A.
     Avaliar N.CONTAMINANTE antes de CONTAMINANTE (substring). Demais linhas: regra legado BA/LI/PE/AV/... */
  IF REGEXP_LIKE(
       UPPER(NVL(V_CODLINHASEPAR, '') || ' ' || NVL(V_DESCLINHASEPAR, '')),
       'N\.?\s*CONTAMINANTE|NAO\s+CONTAMINANTE|N' || CHR(195) || 'O\s+CONTAMINANTE'
     )
     OR UPPER(TRIM(NVL(V_CODLINHASEPAR, 'X'))) IN ('SN', 'SO') THEN
    V_TIPO_PRODUTO := 'A';
    V_DESC_TIPO_PRODUTO := 'ALIMENTICIO';
  ELSIF REGEXP_LIKE(
       UPPER(NVL(V_CODLINHASEPAR, '') || ' ' || NVL(V_DESCLINHASEPAR, '')),
       'CONTAMINANTE'
     )
     OR UPPER(TRIM(NVL(V_CODLINHASEPAR, 'X'))) IN ('SA', 'SP') THEN
    V_TIPO_PRODUTO := 'N';
    V_DESC_TIPO_PRODUTO := 'NAO ALIMENTICIO';
  ELSIF REGEXP_LIKE(
       UPPER(NVL(V_CODLINHASEPAR, '') || ' ' || NVL(V_DESCLINHASEPAR, '')),
       '(BA|LI|PE|AV|BAZAR|LIMPEZA|PERFUMARIA|AVARIA|BLOCA|BLOQ)'
     ) THEN
    V_TIPO_PRODUTO := 'N';
    V_DESC_TIPO_PRODUTO := 'NAO ALIMENTICIO';
  ELSE
    V_TIPO_PRODUTO := 'A';
    V_DESC_TIPO_PRODUTO := 'ALIMENTICIO';
  END IF;
  V_QTDEMB := NVL(V_QTDEMB, 1);
  V_PESO := NVL(V_PESO, 1);
  V_ALTURA := NVL(V_ALTURA, 1);
  V_LARGURA := NVL(V_LARGURA, 1);
  V_COMP := NVL(V_COMP, 1);
  /* Produtivo na remessa: somente se ja existir montagem C5 (MLO_MONTAGEMSORTER).
     Sem fallback MIN(CODPRODUTIVO): operador real vem do retorno Invent (Velox). */
  IF V_COD_PROD IS NOT NULL THEN
    SELECT COUNT(*)
      INTO V_TMP_COUNT
      FROM CONSINCO.MLO_PRODUTIVO p
     WHERE p.NROEMPRESA = V_NROEMPRESA
       AND p.CODPRODUTIVO = V_COD_PROD
       AND NVL(p.STATUSPRODUTIVO, 'A') = 'A';
    IF V_TMP_COUNT = 0 THEN
      V_COD_PROD := NULL;
    END IF;
  END IF;
  IF V_COD_PROD IS NOT NULL THEN
    BEGIN
      SELECT SUBSTR(NVL(p.NOMEREDUZ, p.PRODUTIVO), 1, 40),
	     SUBSTR(p.CODRH, 1, 30)
	INTO V_PROD, V_COD_RH
	FROM CONSINCO.MLO_PRODUTIVO p
       WHERE p.NROEMPRESA = V_NROEMPRESA
	 AND p.CODPRODUTIVO = V_COD_PROD
	 AND NVL(p.STATUSPRODUTIVO, 'A') = 'A'
	 AND ROWNUM = 1;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
	V_COD_PROD := NULL;
	V_PROD := NULL;
	V_COD_RH := NULL;
    END;
  ELSE
    V_COD_PROD := NULL;
    V_PROD := NULL;
    V_COD_RH := NULL;
  END IF;
  V_ID_BASE := ABS(DBMS_UTILITY.GET_HASH_VALUE(P_CODBARRAETQ, 1, 2000000000)) + 1000;
  IF V_JA_BUF_ETQ = 0 THEN
    INSERT INTO CD2.DD_SORTER_EVENTO_CTRL (
      ID_EVENTO, CODBARRAETQ, ORIGEM, STATUS_ORIGEM, NROCARGA, NROEMPRESA,
      FKMISSAO, FKVOLUME, DTA_EVENTO_ORIGEM, DTA_CAPTURA, HASH_EVENTO, OBS
    ) VALUES (
      CD2.SQ_DD_SORTER_EVENTO_CTRL.NEXTVAL,
      P_CODBARRAETQ,
      'ENVIO',
      'ENVIO_BUFFER',
      V_NROCARGA,
      V_NROEMPRESA,
      V_ID_BASE,
      V_ID_BASE,
      SYSDATE,
      SYSDATE,
      P_CODBARRAETQ || '|ENVIO|BUFFER|' || NVL(V_TIPESPECIE, '?') || '|' || V_SEQPRODUTO
	|| '|' || NVL(TO_CHAR(V_ETIQUETA_ORIGEM), '0'),
      'AGUARDANDO LEVA DESTINO. ETIQ_ORIGEM=' || NVL(TO_CHAR(V_ETIQUETA_ORIGEM), '-')
	|| ' MAX_LEVA=' || TO_CHAR(C_LEVA_MAX_VOLUMES)
    );
    COMMIT;
  END IF;
  /* Leva: apenas volumes ainda nao ENVIADO_INVENT para este destino (palete+loja).
     Fecha fragmentos de ate C_LEVA_MAX_VOLUMES volumes. Sobra menor que o limite
     fecha quando todos os pendentes do destino ja estao prontos/em buffer.
     Cada leva gera SEQLOTE distinto em GPT_INTEGRA_REMESSA (UK_INTEGR_PEDIDOS). */
  SELECT COUNT(DISTINCT c.CODBARRAETQ)
    INTO V_QTD_PENDENTE
    FROM CD2.DDV_SORTER_CORRELACAO_ENRIQ c
    JOIN CONSINCO.MLO_INTEGRACAOSORTER i_c
      ON i_c.CODBARRAETQ = c.CODBARRAETQ
   WHERE c.NROCARGA = V_NROCARGA
     AND c.NROEMPRESA = V_NROEMPRESA
     AND c.SEQPRODUTO = V_SEQPRODUTO
     AND c.TIPESPECIE = V_TIPESPECIE
     AND NVL(i_c.ETIQUETAORIGEM, -1) = NVL(V_ETIQUETA_ORIGEM, -1)
     AND NOT EXISTS (
	   SELECT 1
	     FROM CD2.DD_SORTER_EVENTO_CTRL e
	    WHERE e.CODBARRAETQ = c.CODBARRAETQ
	      AND e.ORIGEM = 'ENVIO'
	      AND e.STATUS_ORIGEM IN ('ENVIADO_INVENT', 'ENVIO_AGG_INVENT')
	 );
  IF V_QTD_PENDENTE = 0 THEN
    RETURN;
  END IF;
  SELECT COUNT(DISTINCT c.CODBARRAETQ)
    INTO V_QTD_PRONTA
    FROM CD2.DDV_SORTER_CORRELACAO_ENRIQ c
    JOIN CONSINCO.MLO_INTEGRACAOSORTER i_c
      ON i_c.CODBARRAETQ = c.CODBARRAETQ
   WHERE c.NROCARGA = V_NROCARGA
     AND c.NROEMPRESA = V_NROEMPRESA
     AND c.SEQPRODUTO = V_SEQPRODUTO
     AND c.TIPESPECIE = V_TIPESPECIE
     AND NVL(i_c.ETIQUETAORIGEM, -1) = NVL(V_ETIQUETA_ORIGEM, -1)
     AND NOT EXISTS (
	   SELECT 1
	     FROM CD2.DD_SORTER_EVENTO_CTRL e
	    WHERE e.CODBARRAETQ = c.CODBARRAETQ
	      AND e.ORIGEM = 'ENVIO'
	      AND e.STATUS_ORIGEM IN ('ENVIADO_INVENT', 'ENVIO_AGG_INVENT')
	 )
     AND (
	   UPPER(TRIM(NVL(c.TIPOCARGA, 'E'))) = 'R'
	OR NVL(c.QTD_EMB_SEPARADA, 0) > 0
	 )
     AND EXISTS (
	   SELECT 1
	     FROM CD2.DD_SORTER_EVENTO_CTRL e
	    WHERE e.CODBARRAETQ = c.CODBARRAETQ
	      AND e.ORIGEM = 'ENVIO'
	      AND e.STATUS_ORIGEM = 'ENVIO_BUFFER'
	 );
  IF V_QTD_PRONTA < C_LEVA_MAX_VOLUMES AND V_QTD_PRONTA < V_QTD_PENDENTE THEN
    RETURN;
  END IF;
  SELECT COUNT(*)
    INTO V_NUM_LEVAS_ENV
    FROM (
	  SELECT 1
	    FROM CD2.DD_SORTER_EVENTO_CTRL e
	    JOIN CD2.DDV_SORTER_CORRELACAO_ENRIQ c
	      ON c.CODBARRAETQ = e.CODBARRAETQ
	    JOIN CONSINCO.MLO_INTEGRACAOSORTER i_c
	      ON i_c.CODBARRAETQ = c.CODBARRAETQ
	   WHERE e.ORIGEM = 'ENVIO'
	     AND e.STATUS_ORIGEM = 'ENVIADO_INVENT'
	     AND NVL(e.OBS, ' ') LIKE 'ENVIO INTEGRACAO TOTAL DESTINO%'
	     AND c.NROCARGA = V_NROCARGA
	     AND c.NROEMPRESA = V_NROEMPRESA
	     AND c.SEQPRODUTO = V_SEQPRODUTO
	     AND c.TIPESPECIE = V_TIPESPECIE
	     AND NVL(i_c.ETIQUETAORIGEM, -1) = NVL(V_ETIQUETA_ORIGEM, -1)
	   GROUP BY REGEXP_REPLACE(REGEXP_SUBSTR(NVL(e.OBS, ' '), 'SEQLOTE=[0-9]+'), '^SEQLOTE=', '')
	 );
  V_LEVA_NUM := NVL(V_NUM_LEVAS_ENV, 0) + 1;
  V_SEQLOTE := F_SEQLOTE_LEVA(V_ETIQUETA_ORIGEM, V_LEVA_NUM, V_TIPESPECIE, P_CODBARRAETQ);
  V_QTD_GPT := LEAST(V_QTD_PRONTA, C_LEVA_MAX_VOLUMES);
  V_DESC := F_SANITIZA_INVENT(SUBSTR(V_DESC, 1, 50));
  V_PROD := F_SANITIZA_INVENT(SUBSTR(V_PROD, 1, 40));
  V_ROTA := F_SANITIZA_INVENT(V_ROTA);
  V_CODRUA := F_SANITIZA_INVENT(V_CODRUA);
  V_CODACESSO := F_SANITIZA_INVENT(NVL(V_CODACESSO, TO_CHAR(V_SEQPRODUTO)));
  V_COD_RH := F_SANITIZA_INVENT(V_COD_RH);
  V_DESC_TIPO_PRODUTO := F_SANITIZA_INVENT(V_DESC_TIPO_PRODUTO);
  EXECUTE IMMEDIATE
    'SELECT COUNT(*) FROM "GPT_INTEGRA_REMESSA"@INVENT
      WHERE EMPRESA = :1 AND LOJA = :2 AND ONDA = :3 AND SEQPRODUTO = :4 AND SEQLOTE = :5'
    INTO V_EXISTE
    USING V_NROEMPRESA, V_LOJA, V_NROCARGA, V_SEQPRODUTO, V_SEQLOTE;
  IF V_EXISTE > 0 THEN
    BEGIN
      EXECUTE IMMEDIATE
	'SELECT NVL(QUANTIDADE, 0), NVL(STATUS, ''?'')
	   FROM "GPT_INTEGRA_REMESSA"@INVENT
	  WHERE EMPRESA = :1 AND LOJA = :2 AND ONDA = :3 AND SEQPRODUTO = :4 AND SEQLOTE = :5'
	INTO V_QTD_ATUAL, V_STATUS_GPT
	USING V_NROEMPRESA, V_LOJA, V_NROCARGA, V_SEQPRODUTO, V_SEQLOTE;
    EXCEPTION
      WHEN OTHERS THEN
	V_QTD_ATUAL := 0;
	V_STATUS_GPT := NULL;
    END;
    IF UPPER(TRIM(NVL(V_STATUS_GPT, ' '))) = 'INTEGRADO' THEN
      /* Leva ja integrada na Velox (reprocesso idempotente): marca volumes sem regravar GPT. */
      NULL;
    ELSE
      EXECUTE IMMEDIATE
	'UPDATE "GPT_INTEGRA_REMESSA"@INVENT
	    SET QUANTIDADE = :1,
		ROTA = :2,
		STATUS = :3
	  WHERE EMPRESA = :4 AND LOJA = :5 AND ONDA = :6 AND SEQPRODUTO = :7 AND SEQLOTE = :8'
	USING V_QTD_GPT, V_ROTA, C_STATUS_GPT_ENV,
	      V_NROEMPRESA, V_LOJA, V_NROCARGA, V_SEQPRODUTO, V_SEQLOTE;
    END IF;
  ELSE
    EXECUTE IMMEDIATE
      'INSERT INTO "GPT_INTEGRA_REMESSA"@INVENT
	(EMPRESA, TIPO_CARGA, DESCRICAO_TPO_CARGA, TIPO_PRODUTO, DESCRICAO_TIPO_PRODUTO,
	 ONDA, ORDEM_SEPARACAO, LOJA, ROTA, CODRUA, SEQPRODUTO, CODACESSO, QTDEMBALAGEM, QUANTIDADE, SEQLOTE,
	 DESCRICAO, PESO, ALTURA, LARGURA, COMPRIMENTO, COD_PRODUTIVO, COD_RH, PRODUTIVO, STATUS)
       VALUES
	(:1, :2, :3, :4, :5,
	 :6, :7, :8, :9, :10, :11, :12, :13, :14, :15,
	 :16, :17, :18, :19, :20, :21, :22, :23, :24)'
      USING
	V_NROEMPRESA,
	F_SANITIZA_INVENT(V_TIPOCARGA),
	F_SANITIZA_INVENT(SUBSTR(
	  CASE UPPER(TRIM(NVL(V_TIPOCARGA, 'E')))
	    WHEN 'E' THEN 'EXPEDICAO'
	    WHEN 'R' THEN 'RECEBIMENTO'
	    WHEN 'A' THEN 'ARMAZENADA'
	    ELSE 'EXPEDICAO'
	  END,
	  1,
	  40
	)),
	V_TIPO_PRODUTO,
	V_DESC_TIPO_PRODUTO,
	V_NROCARGA,
	V_ORDEM_SEPAR,
	V_LOJA,
	V_ROTA,
	V_CODRUA,
	V_SEQPRODUTO,
	V_CODACESSO,
	V_QTDEMB,
	V_QTD_GPT,
	V_SEQLOTE,
	V_DESC,
	V_PESO,
	V_ALTURA,
	V_LARGURA,
	V_COMP,
	V_COD_PROD,
	V_COD_RH,
	V_PROD,
	C_STATUS_GPT_ENV;
  END IF;
  COMMIT;
  FOR R_ETQ IN (
    SELECT CODBARRAETQ
      FROM (
	    SELECT c.CODBARRAETQ,
		   ROW_NUMBER() OVER (ORDER BY MIN(e_buf.DTA_CAPTURA), c.CODBARRAETQ) AS RN
	      FROM CD2.DDV_SORTER_CORRELACAO_ENRIQ c
	      JOIN CONSINCO.MLO_INTEGRACAOSORTER i_c
		ON i_c.CODBARRAETQ = c.CODBARRAETQ
	      JOIN CD2.DD_SORTER_EVENTO_CTRL e_buf
		ON e_buf.CODBARRAETQ = c.CODBARRAETQ
	       AND e_buf.ORIGEM = 'ENVIO'
	       AND e_buf.STATUS_ORIGEM = 'ENVIO_BUFFER'
	     WHERE c.NROCARGA = V_NROCARGA
	       AND c.NROEMPRESA = V_NROEMPRESA
	       AND c.SEQPRODUTO = V_SEQPRODUTO
	       AND c.TIPESPECIE = V_TIPESPECIE
	       AND NVL(i_c.ETIQUETAORIGEM, -1) = NVL(V_ETIQUETA_ORIGEM, -1)
	       AND NOT EXISTS (
		     SELECT 1
		       FROM CD2.DD_SORTER_EVENTO_CTRL e
		      WHERE e.CODBARRAETQ = c.CODBARRAETQ
			AND e.ORIGEM = 'ENVIO'
			AND e.STATUS_ORIGEM IN ('ENVIADO_INVENT', 'ENVIO_AGG_INVENT')
		   )
	       AND (
		     UPPER(TRIM(NVL(c.TIPOCARGA, 'E'))) = 'R'
		  OR NVL(c.QTD_EMB_SEPARADA, 0) > 0
		   )
	     GROUP BY c.CODBARRAETQ
	   )
     WHERE RN <= V_QTD_GPT
  ) LOOP
    SELECT COUNT(*)
      INTO V_TMP_COUNT
      FROM CD2.DD_SORTER_EVENTO_CTRL e
     WHERE e.CODBARRAETQ = R_ETQ.CODBARRAETQ
       AND e.ORIGEM = 'ENVIO'
       AND e.STATUS_ORIGEM = 'ENVIADO_INVENT';
    IF V_TMP_COUNT = 0 THEN
      INSERT INTO CD2.DD_SORTER_EVENTO_CTRL (
	ID_EVENTO, CODBARRAETQ, ORIGEM, STATUS_ORIGEM, NROCARGA, NROEMPRESA,
	FKMISSAO, FKVOLUME, DTA_EVENTO_ORIGEM, DTA_CAPTURA, HASH_EVENTO, OBS
      ) VALUES (
	CD2.SQ_DD_SORTER_EVENTO_CTRL.NEXTVAL,
	R_ETQ.CODBARRAETQ,
	'ENVIO',
	'ENVIADO_INVENT',
	V_NROCARGA,
	V_NROEMPRESA,
	V_ID_BASE,
	V_ID_BASE,
	SYSDATE,
	SYSDATE,
	R_ETQ.CODBARRAETQ || '|ENVIO|ENVIADO|TOTAL|' || NVL(V_TIPESPECIE, '?') || '|' || V_SEQPRODUTO || '|' || V_SEQLOTE,
	'ENVIO INTEGRACAO TOTAL DESTINO. ROTA=' || V_ROTA
	  || ' SEQLOTE=' || V_SEQLOTE
	  || ' LEVA=' || TO_CHAR(V_LEVA_NUM)
	  || ' ETIQ_ORIGEM=' || NVL(TO_CHAR(V_ETIQUETA_ORIGEM), '-')
	  || ' QTD=' || TO_CHAR(V_QTD_GPT)
      );
    END IF;
  END LOOP;
  COMMIT;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    ROLLBACK;
    INSERT INTO CD2.DD_SORTER_EVENTO_CTRL (
      ID_EVENTO, CODBARRAETQ, ORIGEM, STATUS_ORIGEM, DTA_EVENTO_ORIGEM, DTA_CAPTURA, HASH_EVENTO, OBS
    ) VALUES (
      CD2.SQ_DD_SORTER_EVENTO_CTRL.NEXTVAL, P_CODBARRAETQ, 'ENVIO', 'SEM_DADOS',
      SYSDATE, SYSDATE,
      P_CODBARRAETQ || '|ENVIO|SEM_DADOS|' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
      'ETIQUETA NAO ENCONTRADA PARA ENVIO NAS VIEWS CD2.'
    );
    COMMIT;
  WHEN OTHERS THEN
    ROLLBACK;
    V_ERR := SUBSTR(SQLERRM, 1, 3500);
    INSERT INTO CD2.DD_SORTER_EVENTO_CTRL (
      ID_EVENTO, CODBARRAETQ, ORIGEM, STATUS_ORIGEM, NROCARGA, NROEMPRESA,
      DTA_EVENTO_ORIGEM, DTA_CAPTURA, HASH_EVENTO, OBS
    ) VALUES (
      CD2.SQ_DD_SORTER_EVENTO_CTRL.NEXTVAL, P_CODBARRAETQ, 'ENVIO', 'ERRO_ENVIO',
      V_NROCARGA, V_NROEMPRESA, SYSDATE, SYSDATE,
      P_CODBARRAETQ || '|ENVIO|ERRO_ENVIO|' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
      V_ERR
    );
    COMMIT;
END;
