-- =============================================================================
-- PROCEDURE: DD_PRC_FECHA_C5_ETIQUETA
-- Exportado de CD2@2026-07-01 (fonte: banco remoto)
-- =============================================================================

CREATE OR REPLACE PROCEDURE "DD_PRC_FECHA_C5_ETIQUETA" (
  P_CODBARRAETQ IN VARCHAR2
) AS
  V_STATUS_SORTER  VARCHAR2(40);
  V_STATUS_CONC    VARCHAR2(40);
  V_C5_PROC_INT    VARCHAR2(1);
  V_C5_PROC_MONT   VARCHAR2(1);
  V_QTD_SOL	   NUMBER;
  V_QTD_SEP	   NUMBER;
  V_QTD_CAN	   NUMBER;
  V_NROEMPRESA	   NUMBER;
  V_TIPESPECIE	   VARCHAR2(10);
  V_PALLET_INVENT  VARCHAR2(200);
  V_SEQPALETE	   NUMBER;
  V_CODPROD_INVENT NUMBER;
  V_DTA_ABERTURA   DATE;
  V_DTA_FECHAMENTO DATE;
  V_NROCARGA	   NUMBER;
  V_SEQPRODUTO	   NUMBER;
  V_TIPOCARGA	   VARCHAR2(2);
  V_CODPROD_PADRAO NUMBER;
  V_CODPROD_EFETIVO NUMBER;
  V_TMP_COUNT	   NUMBER;
  V_DESC_PRODUTO   VARCHAR2(250);
  V_TIP_ARMAZ	   VARCHAR2(10);
  V_PESO_BRUTO	   NUMBER;
  V_MCUB	   NUMBER;
  V_PESAVEL	   VARCHAR2(1);
  V_CODRH_EFETIVO  VARCHAR2(50);
  V_NOME_PROD_EF   VARCHAR2(100);
  V_DESC_TIPESP    VARCHAR2(100);
  V_IND_BRACO	   VARCHAR2(1);
  V_IND_PALETECHK  VARCHAR2(1);
  V_SEQPALETEQTDE_DER NUMBER;
  V_SEQPALETERF_DER NUMBER;
  V_SEQCARREG_PALETE NUMBER;
  V_SEQPALETE_VOLUME NUMBER;
  V_ID_GPT_RETORNO NUMBER;
  V_SEQLOTE	   NUMBER;
  V_LOJA_DESTINO   NUMBER;
  V_QTD_PEND_DEST  NUMBER;
  V_CNT_PALLET_CAND NUMBER := 0;
  V_ULT_FECHA_LOG   VARCHAR2(40);
  V_CACHE_DEST_KEY  VARCHAR2(200);
  V_CACHE_CNT_KEY   VARCHAR2(200);
  C_USU_MONTAGEM_SORTER CONSTANT VARCHAR2(20) := 'INVENT';
BEGIN
  SELECT NVL(STATUS_SORTER, STATUS_VOLUME)
    INTO V_STATUS_SORTER
    FROM CD2.DDV_SORTER_CORRELACAO
   WHERE CODBARRAETQ = P_CODBARRAETQ
     AND ROWNUM = 1;
  SELECT STATUS_CONCILIACAO
    INTO V_STATUS_CONC
    FROM CD2.DDV_SORTER_PENDENCIAS
   WHERE CODBARRAETQ = P_CODBARRAETQ
     AND ROWNUM = 1;
  SELECT QTD_EMB_SOLICITADA, QTD_EMB_SEPARADA, QTD_EMB_CANCELADA
    INTO V_QTD_SOL, V_QTD_SEP, V_QTD_CAN
    FROM CD2.DDV_SORTER_CORRELACAO_ENRIQ
   WHERE CODBARRAETQ = P_CODBARRAETQ
     AND ROWNUM = 1;
  SELECT NVL(MAX(INDPROCESSADO), 'N')
    INTO V_C5_PROC_INT
    FROM CONSINCO.MLO_INTEGRACAOSORTER
   WHERE CODBARRAETQ = P_CODBARRAETQ;
  SELECT MAX(NROEMPRESA), MAX(TIPESPECIE)
    INTO V_NROEMPRESA, V_TIPESPECIE
    FROM CONSINCO.MLO_INTEGRACAOSORTER
   WHERE CODBARRAETQ = P_CODBARRAETQ;
  SELECT MAX(NROCARGA), MAX(SEQPRODUTO), MAX(TIPOCARGA)
    INTO V_NROCARGA, V_SEQPRODUTO, V_TIPOCARGA
    FROM CONSINCO.MLO_INTEGRACAOSORTER
   WHERE CODBARRAETQ = P_CODBARRAETQ;
  SELECT NVL(MAX(INDPROCESSADO), 'N')
    INTO V_C5_PROC_MONT
    FROM CONSINCO.MLO_MONTAGEMSORTER
   WHERE CODBARRAETQ = P_CODBARRAETQ;
  /* Recebimento (R): nao usa MLO_CARGAEPRODUTO; elegivel com retorno Invent (mesma regra do envio 021). */
  IF UPPER(TRIM(NVL(V_TIPOCARGA, 'E'))) = 'R'
     AND V_STATUS_SORTER IN ('INDUZIDO', 'RETORNO_PRODUTO') THEN
    V_QTD_SOL := NVL(V_QTD_SOL, 1);
    V_QTD_SEP := GREATEST(NVL(V_QTD_SEP, 0), 1);
  END IF;
  IF V_STATUS_SORTER IN ('INDUZIDO', 'RETORNO_PRODUTO')
     AND (
	   UPPER(TRIM(NVL(V_TIPOCARGA, 'E'))) = 'R'
	OR (V_QTD_SOL IS NOT NULL AND NVL(V_QTD_SEP, 0) > 0)
	 ) THEN
    IF REGEXP_LIKE(TRIM(NVL(V_TIPESPECIE, 'X')), '^[0-9]+$') THEN
      V_SEQLOTE := TO_NUMBER(TRIM(V_TIPESPECIE));
    ELSE
      V_SEQLOTE := ABS(MOD(DBMS_UTILITY.GET_HASH_VALUE(NVL(V_TIPESPECIE, P_CODBARRAETQ), 1, 999999), 999999));
    END IF;
    BEGIN
      SELECT TO_NUMBER(REGEXP_SUBSTR(TRIM(t.DESCTIPESPECIE), '^[0-9]+'))
	INTO V_LOJA_DESTINO
	FROM CONSINCO.MLO_TIPESPECIE t
       WHERE t.NROEMPRESA = V_NROEMPRESA
	 AND t.TIPESPECIE = V_TIPESPECIE
	 AND REGEXP_LIKE(TRIM(t.DESCTIPESPECIE), '^[0-9]+')
	 AND ROWNUM = 1;
    EXCEPTION
      WHEN OTHERS THEN
	IF REGEXP_LIKE(TRIM(NVL(V_TIPESPECIE, 'X')), '^[0-9]+$') THEN
	  V_LOJA_DESTINO := 1000 + TO_NUMBER(TRIM(V_TIPESPECIE));
	ELSE
	  V_LOJA_DESTINO := V_NROEMPRESA;
	END IF;
    END;
    V_CACHE_DEST_KEY := V_NROCARGA || '|' || V_NROEMPRESA || '|' || V_TIPESPECIE || '|' ||
			V_SEQPRODUTO || '|' || UPPER(TRIM(NVL(V_TIPOCARGA, 'E')));
    IF NOT CD2.DD_PKG_FECHA_CACHE.GET_QTD_PEND(V_CACHE_DEST_KEY, V_QTD_PEND_DEST) THEN
      SELECT COUNT(*)
	INTO V_QTD_PEND_DEST
	FROM CD2.DDV_SORTER_CORRELACAO_ENRIQ e
       WHERE e.NROCARGA = V_NROCARGA
	 AND e.NROEMPRESA = V_NROEMPRESA
	 AND e.TIPESPECIE = V_TIPESPECIE
	 AND e.SEQPRODUTO = V_SEQPRODUTO
	 AND (
	       UPPER(TRIM(NVL(V_TIPOCARGA, 'E'))) = 'R'
	    OR NVL(e.QTD_EMB_SEPARADA, 0) > 0
	     )
	 AND NOT EXISTS (
	       SELECT 1
		 FROM CONSINCO.MLO_PALETE p
		 JOIN CONSINCO.MLO_PALCARREGRF prf
		   ON prf.SEQPALETERF = p.SEQPALETERF
		WHERE p.NROCARGARECEB = V_NROCARGA
		  AND p.NROEMPRESA = V_NROEMPRESA
		  AND p.SEQPRODUTO = V_SEQPRODUTO
		  AND p.TIPESPECIE = V_TIPESPECIE
		  AND prf.SEQPALETECARREG IS NOT NULL
		  AND prf.SEQPALETEQTDE = CASE
			WHEN REGEXP_LIKE(e.CODBARRAETQ, '[0-9]{7}$')
			  THEN TO_NUMBER(REGEXP_SUBSTR(e.CODBARRAETQ, '[0-9]{7}$'))
			WHEN REGEXP_LIKE(e.CODBARRAETQ, '[0-9]{6}$')
			  THEN TO_NUMBER(REGEXP_SUBSTR(e.CODBARRAETQ, '[0-9]{6}$'))
			ELSE NULL
		      END
	     );
      CD2.DD_PKG_FECHA_CACHE.SET_QTD_PEND(V_CACHE_DEST_KEY, V_QTD_PEND_DEST);
    END IF;
    V_PALLET_INVENT := NULL;
    V_CODPROD_INVENT := NULL;
    V_DTA_ABERTURA := NULL;
    V_DTA_FECHAMENTO := NULL;
    V_ID_GPT_RETORNO := NULL;
    /* Fonte da verdade: GPT_RETORNO_MONTAGEM_PALETES@INVENT (PALLET/master + SEQPRODUTO + LOJA).
       Palete fisico pode ter varios produtos; cada linha GPT (ID) vincula 1 etiqueta (volume). */
    BEGIN
      SELECT v.PALLET_INVENT, v.SEQPALETECARREG
	INTO V_PALLET_INVENT, V_SEQPALETE
	FROM CD2.DD_SORTER_VINCULO_RETORNO_ETQ v
       WHERE v.CODBARRAETQ = P_CODBARRAETQ;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
	V_PALLET_INVENT := NULL;
	V_SEQPALETE := NULL;
      WHEN OTHERS THEN
	V_PALLET_INVENT := NULL;
	V_SEQPALETE := NULL;
    END;
    IF V_PALLET_INVENT IS NULL AND NVL(V_QTD_PEND_DEST, 0) > 0 THEN
      BEGIN
	EXECUTE IMMEDIATE '
	  SELECT PALLET, COD_PRODUTIVO, DATA_ABERTURA, DATA_FECHAMENTO,
		 ID_GPT_RETORNO_MONTAGEM_PALETES
	    FROM (
	      SELECT r.PALLET,
			     r.COD_PRODUTIVO,
			     r.DATA_ABERTURA,
			     r.DATA_FECHAMENTO,
			     r.ID_GPT_RETORNO_MONTAGEM_PALETES
			FROM "GPT_RETORNO_MONTAGEM_PALETES"@INVENT r
		       WHERE r.EMPRESA = :1
			 AND r.ONDA = :2
			 AND r.SEQPRODUTO = :3
			 AND r.LOJA = :4
			 AND r.LOJA <> r.EMPRESA
			 AND r.DATA_FECHAMENTO IS NOT NULL
			 AND NOT EXISTS (
			       SELECT 1
				 FROM CD2.DD_SORTER_VINCULO_RETORNO_ETQ v
				WHERE v.ID_GPT_RETORNO = r.ID_GPT_RETORNO_MONTAGEM_PALETES
			      )
		      ORDER BY r.DATA_FECHAMENTO DESC, r.ID_GPT_RETORNO_MONTAGEM_PALETES
	    )
	   WHERE ROWNUM = 1'
	  INTO V_PALLET_INVENT, V_CODPROD_INVENT, V_DTA_ABERTURA, V_DTA_FECHAMENTO, V_ID_GPT_RETORNO
	  USING V_NROEMPRESA, V_NROCARGA, V_SEQPRODUTO, V_LOJA_DESTINO;
      EXCEPTION
	WHEN NO_DATA_FOUND THEN
	  V_PALLET_INVENT := NULL;
	WHEN OTHERS THEN
	  V_PALLET_INVENT := NULL;
      END;
      IF V_PALLET_INVENT IS NULL THEN
	V_CACHE_CNT_KEY := V_NROEMPRESA || '|' || V_NROCARGA || '|' || V_SEQPRODUTO ||
			   '|EMP|' || TO_CHAR(NVL(V_QTD_PEND_DEST, 0));
	IF NOT CD2.DD_PKG_FECHA_CACHE.GET_CNT_PALLET(V_CACHE_CNT_KEY, V_CNT_PALLET_CAND) THEN
	  BEGIN
	    EXECUTE IMMEDIATE '
	      SELECT COUNT(DISTINCT px.PALLET)
		FROM (
		       SELECT r.PALLET
			 FROM "GPT_RETORNO_MONTAGEM_PALETES"@INVENT r
			WHERE r.EMPRESA = :1
			  AND r.ONDA = :2
			  AND r.SEQPRODUTO = :3
			  AND r.DATA_FECHAMENTO IS NOT NULL
			  AND r.LOJA = r.EMPRESA
			  AND NOT EXISTS (
				SELECT 1
				  FROM CD2.DD_SORTER_VINCULO_RETORNO_ETQ v
				 WHERE v.ID_GPT_RETORNO = r.ID_GPT_RETORNO_MONTAGEM_PALETES
			       )
			GROUP BY r.PALLET
		       HAVING COUNT(*) = :4
		     ) px'
	      INTO V_CNT_PALLET_CAND
	      USING V_NROEMPRESA, V_NROCARGA, V_SEQPRODUTO, V_QTD_PEND_DEST;
	  EXCEPTION
	    WHEN OTHERS THEN
	      V_CNT_PALLET_CAND := 0;
	  END;
	  CD2.DD_PKG_FECHA_CACHE.SET_CNT_PALLET(V_CACHE_CNT_KEY, V_CNT_PALLET_CAND);
	END IF;
	IF V_CNT_PALLET_CAND = 1 THEN
	  BEGIN
	    EXECUTE IMMEDIATE '
	      SELECT PALLET, COD_PRODUTIVO, DATA_ABERTURA, DATA_FECHAMENTO
		FROM (
		  SELECT r.PALLET,
				 MIN(r.COD_PRODUTIVO) AS COD_PRODUTIVO,
				 MIN(r.DATA_ABERTURA) AS DATA_ABERTURA,
				 MAX(r.DATA_FECHAMENTO) AS DATA_FECHAMENTO
			    FROM "GPT_RETORNO_MONTAGEM_PALETES"@INVENT r
			   WHERE r.EMPRESA = :1
			     AND r.ONDA = :2
			     AND r.SEQPRODUTO = :3
			     AND r.LOJA = r.EMPRESA
			     AND r.DATA_FECHAMENTO IS NOT NULL
			     AND NOT EXISTS (
				   SELECT 1
				     FROM CD2.DD_SORTER_VINCULO_RETORNO_ETQ v
				    WHERE v.ID_GPT_RETORNO = r.ID_GPT_RETORNO_MONTAGEM_PALETES
				  )
			   GROUP BY r.PALLET
			  HAVING COUNT(*) = :4
			  ORDER BY MAX(r.DATA_FECHAMENTO) DESC
		)
	       WHERE ROWNUM = 1'
	      INTO V_PALLET_INVENT, V_CODPROD_INVENT, V_DTA_ABERTURA, V_DTA_FECHAMENTO
	      USING V_NROEMPRESA, V_NROCARGA, V_SEQPRODUTO, V_QTD_PEND_DEST;
	  EXCEPTION
	    WHEN OTHERS THEN
	      V_PALLET_INVENT := NULL;
	  END;
	END IF;
      END IF;
    ELSIF V_PALLET_INVENT IS NOT NULL THEN
      BEGIN
	EXECUTE IMMEDIATE '
	  SELECT MIN(r.COD_PRODUTIVO), MIN(r.DATA_ABERTURA), MAX(r.DATA_FECHAMENTO)
	    FROM "GPT_RETORNO_MONTAGEM_PALETES"@INVENT r
	   WHERE r.EMPRESA = :1
	     AND r.ONDA = :2
	     AND r.SEQPRODUTO = :3
	     AND r.PALLET = :4'
	  INTO V_CODPROD_INVENT, V_DTA_ABERTURA, V_DTA_FECHAMENTO
	  USING V_NROEMPRESA, V_NROCARGA, V_SEQPRODUTO, V_PALLET_INVENT;
      EXCEPTION
	WHEN OTHERS THEN
	  NULL;
      END;
    END IF;
    /* Master obrigatoriamente coerente com retorno Invent deste SEQPRODUTO. */
    IF V_PALLET_INVENT IS NOT NULL AND V_SEQPRODUTO IS NOT NULL THEN
      BEGIN
	EXECUTE IMMEDIATE '
	  SELECT COUNT(*)
	    FROM "GPT_RETORNO_MONTAGEM_PALETES"@INVENT r
	   WHERE r.EMPRESA = :1
	     AND r.ONDA = :2
	     AND r.SEQPRODUTO = :3
	     AND r.PALLET = :4
	     AND r.DATA_FECHAMENTO IS NOT NULL'
	  INTO V_TMP_COUNT
	  USING V_NROEMPRESA, V_NROCARGA, V_SEQPRODUTO, V_PALLET_INVENT;
	IF V_TMP_COUNT = 0 THEN
	  V_PALLET_INVENT := NULL;
	  V_SEQPALETE := NULL;
	END IF;
      EXCEPTION
	WHEN OTHERS THEN
	  NULL;
      END;
    END IF;
    IF REGEXP_LIKE(NVL(V_PALLET_INVENT, ''), '^[Mm][0-9]+$') THEN
      V_SEQPALETE := TO_NUMBER(SUBSTR(V_PALLET_INVENT, 2));
    ELSIF REGEXP_LIKE(NVL(V_PALLET_INVENT, ''), '^[0-9]+$') THEN
      V_SEQPALETE := TO_NUMBER(V_PALLET_INVENT);
    ELSE
      V_SEQPALETE := NULL;
    END IF;
    /* Volume na C5: sufixo numerico da etiqueta (7 digitos no formato atual, fallback 6). */
    IF REGEXP_LIKE(P_CODBARRAETQ, '[0-9]{7}$') THEN
      V_SEQPALETEQTDE_DER := TO_NUMBER(REGEXP_SUBSTR(P_CODBARRAETQ, '[0-9]{7}$'));
    ELSIF REGEXP_LIKE(P_CODBARRAETQ, '[0-9]{6}$') THEN
      V_SEQPALETEQTDE_DER := TO_NUMBER(REGEXP_SUBSTR(P_CODBARRAETQ, '[0-9]{6}$'));
    ELSE
      V_SEQPALETEQTDE_DER := NULL;
    END IF;
    BEGIN
      IF V_SEQPALETEQTDE_DER IS NOT NULL THEN
	SELECT pq.SEQPALETERF
	  INTO V_SEQPALETERF_DER
	  FROM CONSINCO.MLO_PALETE p
	  JOIN CONSINCO.MLO_PALETEQTDE pq ON pq.SEQPALETERF = p.SEQPALETERF
	 WHERE p.NROEMPRESA = V_NROEMPRESA
	   AND p.NROCARGARECEB = V_NROCARGA
	   AND p.SEQPRODUTO = V_SEQPRODUTO
	   AND p.TIPESPECIE = V_TIPESPECIE
	   AND pq.SEQPALETEQTDE = V_SEQPALETEQTDE_DER
	   AND ROWNUM = 1;
      ELSE
	SELECT MAX(p.SEQPALETERF)
	  INTO V_SEQPALETERF_DER
	  FROM CONSINCO.MLO_PALETE p
	 WHERE p.NROEMPRESA = V_NROEMPRESA
	   AND p.NROCARGARECEB = V_NROCARGA
	   AND p.SEQPRODUTO = V_SEQPRODUTO
	   AND p.TIPESPECIE = V_TIPESPECIE;
      END IF;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
	V_SEQPALETERF_DER := NULL;
      WHEN OTHERS THEN
	V_SEQPALETERF_DER := NULL;
    END;
    V_SEQPALETE_VOLUME := NULL;
    IF V_SEQPALETERF_DER IS NOT NULL AND V_SEQPALETEQTDE_DER IS NOT NULL THEN
      BEGIN
	SELECT prf.SEQPALETECARREG
	  INTO V_SEQPALETE_VOLUME
	  FROM CONSINCO.MLO_PALCARREGRF prf
	 WHERE prf.SEQPALETERF = V_SEQPALETERF_DER
	   AND prf.SEQPALETEQTDE = V_SEQPALETEQTDE_DER
	   AND prf.SEQPALETECARREG IS NOT NULL
	   AND ROWNUM = 1;
      EXCEPTION
	WHEN NO_DATA_FOUND THEN
	  V_SEQPALETE_VOLUME := NULL;
	WHEN OTHERS THEN
	  V_SEQPALETE_VOLUME := NULL;
      END;
    END IF;
    BEGIN
      SELECT v.ID_GPT_RETORNO, v.SEQPALETECARREG, v.PALLET_INVENT
	INTO V_ID_GPT_RETORNO, V_SEQPALETE, V_PALLET_INVENT
	FROM CD2.DD_SORTER_VINCULO_RETORNO_ETQ v
       WHERE v.CODBARRAETQ = P_CODBARRAETQ;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
	NULL;
    END;
    IF V_SEQPALETERF_DER IS NOT NULL AND V_PALLET_INVENT IS NOT NULL THEN
      IF V_ID_GPT_RETORNO IS NULL THEN
	BEGIN
	  EXECUTE IMMEDIATE '
	    SELECT MIN(r2.ID_GPT_RETORNO_MONTAGEM_PALETES),
		   MIN(r2.PALLET) KEEP (DENSE_RANK FIRST ORDER BY r2.ID_GPT_RETORNO_MONTAGEM_PALETES)
	      FROM "GPT_RETORNO_MONTAGEM_PALETES"@INVENT r2
	     WHERE r2.EMPRESA = :1
	       AND r2.ONDA = :2
	       AND r2.SEQPRODUTO = :3
	       AND r2.PALLET = :4
	       AND r2.DATA_FECHAMENTO IS NOT NULL
	       AND (
		     (r2.LOJA = :5 AND r2.LOJA <> r2.EMPRESA)
		  OR (r2.LOJA = r2.EMPRESA)
		   )
	       AND NOT EXISTS (
		     SELECT 1
		       FROM CD2.DD_SORTER_VINCULO_RETORNO_ETQ v
		      WHERE v.ID_GPT_RETORNO = r2.ID_GPT_RETORNO_MONTAGEM_PALETES
		   )'
	    INTO V_ID_GPT_RETORNO, V_PALLET_INVENT
	    USING V_NROEMPRESA, V_NROCARGA, V_SEQPRODUTO, V_PALLET_INVENT, V_LOJA_DESTINO;
	EXCEPTION
	  WHEN OTHERS THEN
	    V_ID_GPT_RETORNO := NULL;
	END;
      END IF;
      BEGIN
	SELECT 1
	  INTO V_TMP_COUNT
	  FROM CD2.DD_SORTER_VINCULO_RETORNO_ETQ v
	 WHERE v.CODBARRAETQ = P_CODBARRAETQ;
      EXCEPTION
	WHEN NO_DATA_FOUND THEN
	  IF V_ID_GPT_RETORNO IS NOT NULL THEN
	    BEGIN
	      INSERT INTO CD2.DD_SORTER_VINCULO_RETORNO_ETQ (
		ID_VINCULO, CODBARRAETQ, ID_GPT_RETORNO, NROCARGA, NROEMPRESA,
		SEQPRODUTO, SEQPALETECARREG, PALLET_INVENT, DTA_VINCULO
	      ) VALUES (
		CD2.SQ_DD_SORTER_VINCULO_RETORNO_ETQ.NEXTVAL,
		P_CODBARRAETQ,
		V_ID_GPT_RETORNO,
		V_NROCARGA,
		V_NROEMPRESA,
		V_SEQPRODUTO,
		CASE
		  WHEN REGEXP_LIKE(NVL(V_PALLET_INVENT, ''), '^[Mm][0-9]+$')
		    THEN TO_NUMBER(SUBSTR(V_PALLET_INVENT, 2))
		  WHEN REGEXP_LIKE(NVL(V_PALLET_INVENT, ''), '^[0-9]+$')
		    THEN TO_NUMBER(V_PALLET_INVENT)
		  ELSE NULL
		END,
		V_PALLET_INVENT,
		SYSDATE
	      );
	    EXCEPTION
	      WHEN DUP_VAL_ON_INDEX THEN
		NULL;
	      WHEN OTHERS THEN
		V_ID_GPT_RETORNO := NULL;
	    END;
	  END IF;
      END;
    END IF;
    IF V_SEQPALETE_VOLUME IS NOT NULL THEN
      V_SEQPALETE := V_SEQPALETE_VOLUME;
    ELSIF V_SEQPALETE IS NULL AND V_PALLET_INVENT IS NOT NULL THEN
      IF REGEXP_LIKE(NVL(V_PALLET_INVENT, ''), '^[Mm][0-9]+$') THEN
	V_SEQPALETE := TO_NUMBER(SUBSTR(V_PALLET_INVENT, 2));
      ELSIF REGEXP_LIKE(NVL(V_PALLET_INVENT, ''), '^[0-9]+$') THEN
	V_SEQPALETE := TO_NUMBER(V_PALLET_INVENT);
      END IF;
    END IF;
    IF V_SEQPALETE IS NULL THEN
      BEGIN
	SELECT MAX(e.STATUS_ORIGEM) KEEP (DENSE_RANK LAST ORDER BY e.ID_EVENTO)
	  INTO V_ULT_FECHA_LOG
	  FROM CD2.DD_SORTER_EVENTO_CTRL e
	 WHERE e.CODBARRAETQ = P_CODBARRAETQ
	   AND e.ORIGEM = 'FECHAMENTO';
      EXCEPTION
	WHEN NO_DATA_FOUND THEN
	  V_ULT_FECHA_LOG := NULL;
      END;
      IF NVL(V_ULT_FECHA_LOG, 'X') <> 'AGUARDANDO_MONTAGEM' THEN
	BEGIN
	  INSERT INTO CD2.DD_SORTER_EVENTO_CTRL (
	    ID_EVENTO, CODBARRAETQ, ORIGEM, STATUS_ORIGEM, NROCARGA, NROEMPRESA,
	    DTA_EVENTO_ORIGEM, DTA_CAPTURA, HASH_EVENTO, OBS
	  ) VALUES (
	    CD2.SQ_DD_SORTER_EVENTO_CTRL.NEXTVAL,
	    P_CODBARRAETQ,
	    'FECHAMENTO',
	    'AGUARDANDO_MONTAGEM',
	    V_NROCARGA,
	    V_NROEMPRESA,
	    SYSDATE,
	    SYSDATE,
	    P_CODBARRAETQ || '|FECHA|AGUARD_MONT|' || V_TIPESPECIE,
	    CASE
	      WHEN V_SEQPALETERF_DER IS NULL THEN
		'SEM VOLUME FISICO C5 (SEQPROD=' || NVL(TO_CHAR(V_SEQPRODUTO), '?') || ' TIPESPECIE=' || V_TIPESPECIE || ' LOJA=' || NVL(TO_CHAR(V_LOJA_DESTINO), '?') || ')'
	      WHEN NVL(V_CNT_PALLET_CAND, 0) > 1 THEN
		'RETORNO INVENT AMBIGUO: MAIS DE UM PALLET PARA ' || TO_CHAR(V_QTD_PEND_DEST) || ' VOLUMES PENDENTES (LOJA=' || NVL(TO_CHAR(V_LOJA_DESTINO), '?') || ')'
	      WHEN V_PALLET_INVENT IS NULL THEN
		'SEM LINHA GPT RETORNO (PROD=' || NVL(TO_CHAR(V_SEQPRODUTO), '?') || ' LOJA=' || NVL(TO_CHAR(V_LOJA_DESTINO), '?') || ')'
	      ELSE
		'MASTER INVENT NAO RESOLVIDA (PALLET=' || NVL(V_PALLET_INVENT, '?') || ' PROD=' || NVL(TO_CHAR(V_SEQPRODUTO), '?') || ')'
	    END
	  );
	  COMMIT;
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
	    NULL;
	END;
      END IF;
      RETURN;
    END IF;
    SELECT MIN(p.CODPRODUTIVO)
      INTO V_CODPROD_PADRAO
      FROM CONSINCO.MLO_PRODUTIVO p
     WHERE p.NROEMPRESA = V_NROEMPRESA
       AND NVL(p.STATUSPRODUTIVO, 'A') = 'A';
    IF V_CODPROD_INVENT IS NOT NULL THEN
      SELECT COUNT(*)
	INTO V_TMP_COUNT
	FROM CONSINCO.MLO_PRODUTIVO p
       WHERE p.NROEMPRESA = V_NROEMPRESA
	 AND p.CODPRODUTIVO = V_CODPROD_INVENT
	 AND NVL(p.STATUSPRODUTIVO, 'A') = 'A';
      IF V_TMP_COUNT = 0 THEN
	V_CODPROD_INVENT := NULL;
      END IF;
    END IF;
    V_CODPROD_EFETIVO := NVL(V_CODPROD_INVENT, V_CODPROD_PADRAO);
    V_IND_PALETECHK := CASE WHEN V_SEQPALETE IS NOT NULL THEN 'S' ELSE 'N' END;
    BEGIN
      SELECT SUBSTR(p.DESCCOMPLETA, 1, 250),
	     CAST(NULL AS VARCHAR2(10)),
	     fe.PESOBRUTO,
	     fe.ALTURA * fe.LARGURA * fe.PROFUNDIDADE / 1000000000,
	     CAST(NULL AS VARCHAR2(1))
	INTO V_DESC_PRODUTO, V_TIP_ARMAZ, V_PESO_BRUTO, V_MCUB, V_PESAVEL
	FROM CONSINCO.MAP_PRODUTO p
	LEFT JOIN CONSINCO.MAP_FAMEMBALAGEM fe
	  ON fe.SEQFAMILIA = p.SEQFAMILIA
	 AND fe.QTDEMBALAGEM = (
	      SELECT MAX(x.QTDEMBALAGEM)
		FROM CONSINCO.MLO_CARGAEPRODUTO x
	       WHERE x.NROCARGA = V_NROCARGA
		 AND x.NROEMPRESA = V_NROEMPRESA
		 AND x.SEQPRODUTO = V_SEQPRODUTO
	    )
       WHERE p.SEQPRODUTO = V_SEQPRODUTO;
    EXCEPTION
      WHEN OTHERS THEN
	V_DESC_PRODUTO := NULL;
	V_TIP_ARMAZ := NULL;
	V_PESO_BRUTO := NULL;
	V_MCUB := NULL;
	V_PESAVEL := NULL;
    END;
    BEGIN
      SELECT SUBSTR(p.PRODUTIVO, 1, 100), SUBSTR(p.CODRH, 1, 50)
	INTO V_NOME_PROD_EF, V_CODRH_EFETIVO
	FROM CONSINCO.MLO_PRODUTIVO p
       WHERE p.NROEMPRESA = V_NROEMPRESA
	 AND p.CODPRODUTIVO = V_CODPROD_EFETIVO
	 AND ROWNUM = 1;
    EXCEPTION
      WHEN OTHERS THEN
	V_NOME_PROD_EF := NULL;
	V_CODRH_EFETIVO := NULL;
    END;
    BEGIN
      SELECT SUBSTR(t.DESCTIPESPECIE, 1, 100)
	INTO V_DESC_TIPESP
	FROM CONSINCO.MLO_TIPESPECIE t
       WHERE t.NROEMPRESA = V_NROEMPRESA
	 AND t.TIPESPECIE = V_TIPESPECIE
	 AND ROWNUM = 1;
      V_IND_BRACO := 'N';
    EXCEPTION
      WHEN OTHERS THEN
	V_DESC_TIPESP := NULL;
	V_IND_BRACO := 'N';
    END;
    IF V_SEQPALETE IS NOT NULL
       AND V_SEQPALETERF_DER IS NOT NULL THEN
      BEGIN
	SELECT MAX(c.SEQCARREGAMENTOPORPALETE)
	  INTO V_SEQCARREG_PALETE
	  FROM CONSINCO.MLO_CARREGAMENTOPORPALMASTER c
	 WHERE c.NROEMPRESA = V_NROEMPRESA
	   AND c.SEQPALETECARREG = V_SEQPALETE
	   AND c.SEQPALETERF = V_SEQPALETERF_DER;
      EXCEPTION
	WHEN OTHERS THEN
	  V_SEQCARREG_PALETE := NULL;
      END;
      IF V_SEQCARREG_PALETE IS NULL THEN
	BEGIN
	  SELECT CONSINCO.S_MLO_CARREGAMENTOPORPALETE.NEXTVAL
	    INTO V_SEQCARREG_PALETE
	    FROM DUAL;
	  INSERT INTO CONSINCO.MLO_CARREGAMENTOPORPALETE (
	    SEQCARREGAMENTOPORPALETE,
	    NROEMPRESA,
	    DATAHORAINICIO,
	    NROCARGACOMERCIAL,
	    INDINTEGRADO
	  ) VALUES (
	    V_SEQCARREG_PALETE,
	    V_NROEMPRESA,
	    NVL(V_DTA_ABERTURA, SYSDATE),
	    V_NROCARGA,
	    'N'
	  );
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
	    BEGIN
	      SELECT CONSINCO.S_MLO_CARREGAMENTOPORPALETE.NEXTVAL
		INTO V_SEQCARREG_PALETE
		FROM DUAL;
	      INSERT INTO CONSINCO.MLO_CARREGAMENTOPORPALETE (
		SEQCARREGAMENTOPORPALETE,
		NROEMPRESA,
		DATAHORAINICIO,
		NROCARGACOMERCIAL,
		INDINTEGRADO
	      ) VALUES (
		V_SEQCARREG_PALETE,
		V_NROEMPRESA,
		NVL(V_DTA_ABERTURA, SYSDATE),
		V_NROCARGA,
		'N'
	      );
	    EXCEPTION
	      WHEN OTHERS THEN
		V_SEQCARREG_PALETE := NULL;
	    END;
	  WHEN OTHERS THEN
	    V_SEQCARREG_PALETE := NULL;
	END;
      END IF;
    END IF;
    IF V_SEQPALETE IS NOT NULL THEN
      BEGIN
	EXECUTE IMMEDIATE '
	  MERGE INTO CONSINCO.MLO_PALETECARREG pc
	  USING (
	    SELECT :1 AS SEQPALETECARREG,
		   :2 AS NROEMPRESA,
		   :3 AS NROCARGACARREG,
		   ''M'' AS STATUSCARREG,
		   :4 AS SEQCARREGAMENTOSORTER,
		   SYSDATE AS DTAHORINIMONT,
		   SYSDATE AS DTAHORFINALMONT,
		   :5 AS USUMONTAGEM
	      FROM DUAL
	  ) s
	     ON (pc.SEQPALETECARREG = s.SEQPALETECARREG)
	  WHEN MATCHED THEN
	    UPDATE SET pc.NROEMPRESA = COALESCE(pc.NROEMPRESA, s.NROEMPRESA),
		       pc.NROCARGACARREG = COALESCE(pc.NROCARGACARREG, s.NROCARGACARREG),
		       pc.STATUSCARREG = s.STATUSCARREG,
		       pc.SEQCARREGAMENTOSORTER = COALESCE(pc.SEQCARREGAMENTOSORTER, s.SEQCARREGAMENTOSORTER),
		       pc.DTAHORINIMONT = s.DTAHORINIMONT,
		       pc.DTAHORFINALMONT = s.DTAHORFINALMONT,
		       pc.USUMONTAGEM = s.USUMONTAGEM
	  WHEN NOT MATCHED THEN
	    INSERT (SEQPALETECARREG, NROEMPRESA, NROCARGACARREG, STATUSCARREG, SEQCARREGAMENTOSORTER, DTAHORINIMONT, DTAHORFINALMONT, USUMONTAGEM)
	    VALUES (s.SEQPALETECARREG, s.NROEMPRESA, s.NROCARGACARREG, s.STATUSCARREG, s.SEQCARREGAMENTOSORTER, s.DTAHORINIMONT, s.DTAHORFINALMONT, s.USUMONTAGEM)'
	USING V_SEQPALETE, V_NROEMPRESA, V_NROCARGA, V_SEQPALETE, C_USU_MONTAGEM_SORTER;
      EXCEPTION
	WHEN OTHERS THEN
	  NULL;
      END;
    END IF;
    IF V_SEQPALETE IS NOT NULL
       AND V_SEQPALETERF_DER IS NOT NULL
       AND V_SEQPALETEQTDE_DER IS NOT NULL THEN
      BEGIN
	EXECUTE IMMEDIATE '
	  MERGE INTO CONSINCO.MLO_PALCARREGRF prf
	  USING (
	    SELECT :1 AS SEQPALETECARREG,
		   :2 AS SEQPALETERF,
		   :3 AS SEQPALETEQTDE
	      FROM DUAL
	  ) s
	     ON (prf.SEQPALETERF = s.SEQPALETERF
		 AND prf.SEQPALETEQTDE = s.SEQPALETEQTDE)
	  WHEN MATCHED THEN
	    UPDATE SET prf.SEQPALETECARREG = s.SEQPALETECARREG
	  WHEN NOT MATCHED THEN
	    INSERT (SEQPALETECARREG, SEQPALETERF, SEQPALETEQTDE)
	    VALUES (s.SEQPALETECARREG, s.SEQPALETERF, s.SEQPALETEQTDE)'
	USING V_SEQPALETE, V_SEQPALETERF_DER, V_SEQPALETEQTDE_DER;
      EXCEPTION
	WHEN OTHERS THEN
	  NULL;
      END;
    END IF;
    IF V_SEQPALETE IS NOT NULL
       AND V_SEQPALETERF_DER IS NOT NULL
       AND V_SEQCARREG_PALETE IS NOT NULL THEN
      BEGIN
	EXECUTE IMMEDIATE '
	  MERGE INTO CONSINCO.MLO_CARREGAMENTOPORPALMASTER cpm
	  USING (
	    SELECT :1 AS SEQCARREGAMENTOPORPALETE,
		   :2 AS NROEMPRESA,
		   :3 AS NROCARGA,
		   :4 AS TIPOCARGA,
		   :5 AS SEQPALETECARREG,
		   :6 AS SEQPALETERF,
		   :7 AS DATAHORACARREGAMENTO
	      FROM DUAL
	  ) s
	     ON (cpm.SEQPALETERF = s.SEQPALETERF
		 AND cpm.SEQPALETECARREG = s.SEQPALETECARREG
		 AND cpm.NROEMPRESA = s.NROEMPRESA)
	  WHEN MATCHED THEN
	    UPDATE SET cpm.SEQCARREGAMENTOPORPALETE = COALESCE(cpm.SEQCARREGAMENTOPORPALETE, s.SEQCARREGAMENTOPORPALETE),
		       cpm.NROCARGA = COALESCE(cpm.NROCARGA, s.NROCARGA),
		       cpm.TIPOCARGA = COALESCE(cpm.TIPOCARGA, s.TIPOCARGA),
		       cpm.DATAHORACARREGAMENTO = COALESCE(cpm.DATAHORACARREGAMENTO, s.DATAHORACARREGAMENTO),
		       cpm.STATUS = COALESCE(cpm.STATUS, ''L'')
	  WHEN NOT MATCHED THEN
	    INSERT (
	      SEQCARREGAMENTOPORPALETE,
	      NROEMPRESA,
	      NROCARGA,
	      TIPOCARGA,
	      SEQPALETECARREG,
	      SEQPALETERF,
	      DATAHORACARREGAMENTO,
	      STATUS
	    )
	    VALUES (
	      s.SEQCARREGAMENTOPORPALETE,
	      s.NROEMPRESA,
	      s.NROCARGA,
	      s.TIPOCARGA,
	      s.SEQPALETECARREG,
	      s.SEQPALETERF,
	      s.DATAHORACARREGAMENTO,
	      ''L''
	    )'
	USING V_SEQCARREG_PALETE, V_NROEMPRESA, V_NROCARGA, NVL(V_TIPOCARGA, 'E'),
	      V_SEQPALETE, V_SEQPALETERF_DER, NVL(V_DTA_FECHAMENTO, SYSDATE);
      EXCEPTION
	WHEN OTHERS THEN
	  NULL;
      END;
    END IF;
    IF V_SEQPALETE IS NOT NULL AND V_C5_PROC_INT = 'S' AND V_C5_PROC_MONT = 'S' THEN
      /* Reprocesso: ainda materializa paleteqtde/palcarregrf se faltou (ex. sufixo etiqueta). */
      IF V_SEQPALETERF_DER IS NOT NULL AND V_SEQPALETEQTDE_DER IS NOT NULL THEN
	BEGIN
	  EXECUTE IMMEDIATE '
	    MERGE INTO CONSINCO.MLO_PALCARREGRF prf
	    USING (SELECT :1 sp, :2 rf, :3 qt FROM DUAL) s
	       ON (prf.SEQPALETERF = s.rf AND prf.SEQPALETEQTDE = s.qt)
	    WHEN MATCHED THEN UPDATE SET prf.SEQPALETECARREG = s.sp
	    WHEN NOT MATCHED THEN INSERT (SEQPALETECARREG, SEQPALETERF, SEQPALETEQTDE)
	      VALUES (s.sp, s.rf, s.qt)'
	    USING V_SEQPALETE, V_SEQPALETERF_DER, V_SEQPALETEQTDE_DER;
	EXCEPTION WHEN OTHERS THEN NULL;
	END;
	UPDATE CONSINCO.MLO_PALETEQTDE pq
	   SET pq.SEQPALETECARREG = COALESCE(pq.SEQPALETECARREG, V_SEQPALETE),
	       pq.CODPRODUTIVO = COALESCE(pq.CODPRODUTIVO, V_CODPROD_EFETIVO),
	       pq.DTAHORAMONTAGEMPALETE = COALESCE(pq.DTAHORAMONTAGEMPALETE, V_DTA_FECHAMENTO)
	 WHERE pq.SEQPALETERF = V_SEQPALETERF_DER
	   AND pq.SEQPALETEQTDE = V_SEQPALETEQTDE_DER;
      END IF;
      INSERT INTO CD2.DD_SORTER_EVENTO_CTRL (
	ID_EVENTO, CODBARRAETQ, ORIGEM, STATUS_ORIGEM, DTA_EVENTO_ORIGEM, DTA_CAPTURA, HASH_EVENTO, OBS
      ) VALUES (
	CD2.SQ_DD_SORTER_EVENTO_CTRL.NEXTVAL,
	P_CODBARRAETQ,
	'FECHAMENTO',
	'C5_JA_FECHADO',
	SYSDATE,
	SYSDATE,
	P_CODBARRAETQ || '|FECHA|C5_JA_FECHADO|' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
	'SEM UPDATE. REGISTRO JA PROCESSADO NA C5.'
      );
      COMMIT;
    ELSIF V_SEQPALETE IS NOT NULL THEN
      INSERT INTO CONSINCO.MLO_MONTAGEMSORTER (
	SEQPALETECARREG,
	CODBARRAETQ,
	NROEMPRESA,
	TIPESPECIE,
	CODPRODUTIVO,
	DTAHORINIMONT,
	DTAHORFINALMONT,
	DTAHORALTERACAO,
	INDOPERACAO,
	INDPROCESSADO
      )
      SELECT
	V_SEQPALETE,
	P_CODBARRAETQ,
	V_NROEMPRESA,
	V_TIPESPECIE,
	V_CODPROD_EFETIVO,
	NVL(V_DTA_ABERTURA, SYSDATE),
	NVL(V_DTA_FECHAMENTO, NVL(V_DTA_ABERTURA, SYSDATE)),
	SYSDATE,
	'I',
	'S'
      FROM DUAL
      WHERE NOT EXISTS (
	SELECT 1
	  FROM CONSINCO.MLO_MONTAGEMSORTER m
	 WHERE m.CODBARRAETQ = P_CODBARRAETQ
      );
      UPDATE CONSINCO.MLO_INTEGRACAOSORTER
	 SET INDPROCESSADO = 'S',
	     DTAHORALTERACAO = SYSDATE
       WHERE CODBARRAETQ = P_CODBARRAETQ
	 AND NVL(INDPROCESSADO, 'N') <> 'S';
      UPDATE CONSINCO.MLO_MONTAGEMSORTER
	 SET INDPROCESSADO = 'S',
	     SEQPALETECARREG = NVL(SEQPALETECARREG, V_SEQPALETE),
	     CODPRODUTIVO = CASE
			      WHEN CODPRODUTIVO IS NULL THEN V_CODPROD_EFETIVO
			      WHEN NOT EXISTS (
				     SELECT 1
				       FROM CONSINCO.MLO_PRODUTIVO p
				      WHERE p.NROEMPRESA = V_NROEMPRESA
					AND p.CODPRODUTIVO = CONSINCO.MLO_MONTAGEMSORTER.CODPRODUTIVO
					AND NVL(p.STATUSPRODUTIVO, 'A') = 'A'
				   ) THEN V_CODPROD_EFETIVO
			      ELSE CODPRODUTIVO
			    END,
	     DTAHORINIMONT = NVL(DTAHORINIMONT, NVL(V_DTA_ABERTURA, SYSDATE)),
	     DTAHORFINALMONT = NVL(DTAHORFINALMONT, NVL(V_DTA_FECHAMENTO, NVL(V_DTA_ABERTURA, SYSDATE))),
	     DTAHORALTERACAO = SYSDATE
       WHERE CODBARRAETQ = P_CODBARRAETQ
	 AND NVL(INDPROCESSADO, 'N') <> 'S';
      MERGE INTO CONSINCO.MLO_CHECAGEMSORTER c
      USING (SELECT P_CODBARRAETQ AS CODBARRAETQ, V_NROEMPRESA AS NROEMPRESA, V_TIPESPECIE AS TIPESPECIE FROM DUAL) s
	 ON (c.CODBARRAETQ = s.CODBARRAETQ)
      WHEN MATCHED THEN
	UPDATE SET c.NROEMPRESA = s.NROEMPRESA,
		   c.TIPESPECIE = s.TIPESPECIE,
		   c.INDPALETECHECK = V_IND_PALETECHK,
		   c.INDPROCESSADO = 'S',
		   c.DTAHORALTERACAO = SYSDATE
      WHEN NOT MATCHED THEN
	INSERT (CODBARRAETQ, NROEMPRESA, TIPESPECIE, INDPALETECHECK, INDPROCESSADO, DTAHORALTERACAO)
	VALUES (s.CODBARRAETQ, s.NROEMPRESA, s.TIPESPECIE, V_IND_PALETECHK, 'S', SYSDATE);
      MERGE INTO CONSINCO.MLO_PRODUTIVOSORTER ps
      USING (
	SELECT V_CODPROD_EFETIVO AS CODPRODUTIVO, V_NROEMPRESA AS NROEMPRESA,
	       V_NOME_PROD_EF AS PRODUTIVO, V_CODRH_EFETIVO AS CODRH
	  FROM DUAL
      ) s
	 ON (ps.CODPRODUTIVO = s.CODPRODUTIVO AND ps.NROEMPRESA = s.NROEMPRESA)
      WHEN MATCHED THEN
	UPDATE SET ps.PRODUTIVO = COALESCE(s.PRODUTIVO, ps.PRODUTIVO),
		   ps.CODRH = COALESCE(s.CODRH, ps.CODRH),
		   ps.INDPROCESSADO = 'N',
		   ps.DTAHORALTERACAO = SYSDATE
      WHEN NOT MATCHED THEN
	INSERT (CODPRODUTIVO, PRODUTIVO, CODRH, NROEMPRESA, INDPROCESSADO, INDOPERACAO, DTAHORALTERACAO)
	VALUES (s.CODPRODUTIVO, s.PRODUTIVO, s.CODRH, s.NROEMPRESA, 'N', 'I', SYSDATE);
      MERGE INTO CONSINCO.MLO_TIPESPECIESORTER ts
      USING (
	SELECT V_TIPESPECIE AS TIPESPECIE, V_NROEMPRESA AS NROEMPRESA,
	       V_DESC_TIPESP AS DESCESPECIE, V_IND_BRACO AS INDBRACO
	  FROM DUAL
      ) s
	 ON (ts.TIPESPECIE = s.TIPESPECIE AND ts.NROEMPRESA = s.NROEMPRESA)
      WHEN MATCHED THEN
	UPDATE SET ts.DESCESPECIE = COALESCE(s.DESCESPECIE, ts.DESCESPECIE),
		   ts.INDBRACO = COALESCE(s.INDBRACO, ts.INDBRACO),
		   ts.INDPROCESSADO = 'N',
		   ts.DTAHORALTERACAO = SYSDATE
      WHEN NOT MATCHED THEN
	INSERT (TIPESPECIE, NROEMPRESA, DESCESPECIE, INDBRACO, INDPOSICAOAREABRACO, INDPROCESSADO, DTAHORALTERACAO, INDOPERACAO)
	VALUES (s.TIPESPECIE, s.NROEMPRESA, s.DESCESPECIE, s.INDBRACO, NULL, 'N', SYSDATE, 'I');
      MERGE INTO CONSINCO.MLO_PRODUTOSORTER prd
      USING (
	SELECT V_SEQPRODUTO AS SEQPRODUTO,
	       V_NROEMPRESA AS NROEMPRESA,
	       V_DESC_PRODUTO AS DESCCOMPLETA,
	       V_TIP_ARMAZ AS TIPARMAZENAGEM,
	       V_PESO_BRUTO AS PESOBRUTO,
	       V_MCUB AS METROSCUBICOS,
	       V_PESAVEL AS PESAVEL
	  FROM DUAL
      ) s
	 ON (prd.SEQPRODUTO = s.SEQPRODUTO AND prd.NROEMPRESA = s.NROEMPRESA)
      WHEN MATCHED THEN
	UPDATE SET prd.DESCCOMPLETA = COALESCE(s.DESCCOMPLETA, prd.DESCCOMPLETA),
		   prd.TIPARMAZENAGEM = COALESCE(s.TIPARMAZENAGEM, prd.TIPARMAZENAGEM),
		   prd.PESOBRUTO = COALESCE(s.PESOBRUTO, prd.PESOBRUTO),
		   prd.METROSCUBICOS = COALESCE(s.METROSCUBICOS, prd.METROSCUBICOS),
		   prd.PESAVEL = COALESCE(s.PESAVEL, prd.PESAVEL)
      WHEN NOT MATCHED THEN
	INSERT (SEQPRODUTO, NROEMPRESA, DESCCOMPLETA, TIPARMAZENAGEM, PESOBRUTO, METROSCUBICOS, PESAVEL)
	VALUES (s.SEQPRODUTO, s.NROEMPRESA, s.DESCCOMPLETA, s.TIPARMAZENAGEM, s.PESOBRUTO, s.METROSCUBICOS, s.PESAVEL);
      MERGE INTO CONSINCO.MLO_CARGARECEB cr
      USING (
	SELECT V_NROCARGA AS NROCARGA,
	       V_NROEMPRESA AS NROEMPRESA,
	       'RETORNO SORTER CARGA ' || TO_CHAR(V_NROCARGA) AS DESCRICAO,
	       'C' AS TIPCARGARECEB,
	       V_NROCARGA AS NROCARGAEXPED,
	       NVL(V_DTA_ABERTURA, SYSDATE) AS DTAHORGERACAO,
	       NVL(V_DTA_FECHAMENTO, NVL(V_DTA_ABERTURA, SYSDATE)) AS DTAHORLIBERACAO
	  FROM DUAL
      ) s
	 ON (cr.NROCARGA = s.NROCARGA AND cr.NROEMPRESA = s.NROEMPRESA)
      WHEN MATCHED THEN
	UPDATE SET cr.CODPRODUTIVO = COALESCE(cr.CODPRODUTIVO, V_CODPROD_EFETIVO),
		   cr.STATUSGERACAOSORTER = 'S',
		   cr.STATUSSERVICO = 'F',
		   cr.STATUSCARGA = COALESCE(cr.STATUSCARGA, 'L'),
		   cr.STATUSCONFERENCIA = COALESCE(cr.STATUSCONFERENCIA, 'F'),
		   cr.DTAHORLIBERACAO = COALESCE(cr.DTAHORLIBERACAO, s.DTAHORLIBERACAO),
		   cr.DTAHORGERARMAZENAGEM = COALESCE(cr.DTAHORGERARMAZENAGEM, s.DTAHORLIBERACAO),
		   cr.USULIBERACAO = COALESCE(cr.USULIBERACAO, 'CD2_SORTER')
      WHEN NOT MATCHED THEN
	INSERT (
	  NROCARGA, NROEMPRESA, DESCRICAO, TIPCARGARECEB, NROCARGAEXPED,
	  DTAHORGERACAO, USUGERACAO, DTAHORLIBERACAO, STATUSCARGA, STATUSCONFERENCIA,
	  STATUSGERACAOSORTER, STATUSSERVICO, CODPRODUTIVO
	)
	VALUES (
	  s.NROCARGA, s.NROEMPRESA, s.DESCRICAO, s.TIPCARGARECEB, s.NROCARGAEXPED,
	  s.DTAHORGERACAO, 'CD2_SORTER', s.DTAHORLIBERACAO, 'L', 'F',
	  'S', 'F', V_CODPROD_EFETIVO
	);
      UPDATE CONSINCO.MLO_PALETEQTDE pq
	 SET pq.SEQPALETECARREG = COALESCE(pq.SEQPALETECARREG, V_SEQPALETE),
	     pq.CODPRODUTIVO = COALESCE(pq.CODPRODUTIVO, V_CODPROD_EFETIVO),
	     pq.DTAHORAMONTAGEMPALETE = COALESCE(pq.DTAHORAMONTAGEMPALETE, V_DTA_FECHAMENTO)
       WHERE V_SEQPALETERF_DER IS NOT NULL
	 AND pq.SEQPALETERF = V_SEQPALETERF_DER
	 AND V_SEQPALETEQTDE_DER IS NOT NULL
	 AND pq.SEQPALETEQTDE = V_SEQPALETEQTDE_DER;
      INSERT INTO CD2.DD_SORTER_EVENTO_CTRL (
	ID_EVENTO, CODBARRAETQ, ORIGEM, STATUS_ORIGEM, DTA_EVENTO_ORIGEM, DTA_CAPTURA, HASH_EVENTO, OBS
      ) VALUES (
	CD2.SQ_DD_SORTER_EVENTO_CTRL.NEXTVAL,
	P_CODBARRAETQ,
	'FECHAMENTO',
	CASE
	  WHEN (NVL(V_QTD_SEP, 0) + NVL(V_QTD_CAN, 0) >= V_QTD_SOL) THEN 'C5_FECHADO'
	  ELSE 'C5_FECHADO_COM_DIVERGENCIA'
	END,
	SYSDATE,
	SYSDATE,
	P_CODBARRAETQ || '|FECHA|' ||
	  CASE
	    WHEN (NVL(V_QTD_SEP, 0) + NVL(V_QTD_CAN, 0) >= V_QTD_SOL) THEN 'C5_FECHADO'
	    ELSE 'C5_FECHADO_COM_DIVERGENCIA'
	  END || '|' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
	CASE
	  WHEN (NVL(V_QTD_SEP, 0) + NVL(V_QTD_CAN, 0) >= V_QTD_SOL) THEN
	    'FECHAMENTO CONTROLADO COM STATUS INVENT=' || V_STATUS_SORTER || ' E CONCILIACAO=' || V_STATUS_CONC
	  ELSE
	    'FECHADO COM DIVERGENCIA QUANTITATIVA: SOL=' || TO_CHAR(V_QTD_SOL) ||
	    ' SEP=' || TO_CHAR(NVL(V_QTD_SEP, 0)) ||
	    ' CAN=' || TO_CHAR(NVL(V_QTD_CAN, 0))
	END
      );
      CD2.DD_PKG_FECHA_CACHE.DECR_QTD_PEND(V_CACHE_DEST_KEY);
      COMMIT;
    END IF;
  ELSE
    BEGIN
      SELECT MAX(e.STATUS_ORIGEM) KEEP (DENSE_RANK LAST ORDER BY e.ID_EVENTO)
	INTO V_ULT_FECHA_LOG
	FROM CD2.DD_SORTER_EVENTO_CTRL e
       WHERE e.CODBARRAETQ = P_CODBARRAETQ
	 AND e.ORIGEM = 'FECHAMENTO';
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
	V_ULT_FECHA_LOG := NULL;
    END;
    IF NVL(V_ULT_FECHA_LOG, 'X') <> 'NAO_FECHADO' THEN
      BEGIN
	INSERT INTO CD2.DD_SORTER_EVENTO_CTRL (
	  ID_EVENTO, CODBARRAETQ, ORIGEM, STATUS_ORIGEM, DTA_EVENTO_ORIGEM, DTA_CAPTURA, HASH_EVENTO, OBS
	) VALUES (
	  CD2.SQ_DD_SORTER_EVENTO_CTRL.NEXTVAL,
	  P_CODBARRAETQ,
	  'FECHAMENTO',
	  'NAO_FECHADO',
	  SYSDATE,
	  SYSDATE,
	  P_CODBARRAETQ || '|FECHA|NAO_FECHADO',
	  CASE
	    WHEN V_STATUS_SORTER NOT IN ('INDUZIDO', 'RETORNO_PRODUTO') THEN
	      'STATUS INVENT NAO ELEGIVEL: ' || V_STATUS_SORTER
	    WHEN V_QTD_SOL IS NULL THEN
	      'SEM_BASE_QUANTITATIVA (QTD_SOLICITADA NULA)'
	    WHEN NVL(V_QTD_SEP, 0) = 0 THEN
	      'QTD_SEPARADA_ZERO'
	    WHEN (NVL(V_QTD_SEP, 0) + NVL(V_QTD_CAN, 0) < V_QTD_SOL) THEN
	      'QTD_INSUFICIENTE: SOL=' || TO_CHAR(V_QTD_SOL) ||
	      ' SEP=' || TO_CHAR(NVL(V_QTD_SEP, 0)) ||
	      ' CAN=' || TO_CHAR(NVL(V_QTD_CAN, 0))
	    ELSE
	      'NAO_ELEGIVEL_POR_REGRA_QUANTITATIVA'
	  END
	);
	COMMIT;
      EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
	  NULL;
      END;
    END IF;
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO CD2.DD_SORTER_EVENTO_CTRL (
      ID_EVENTO, CODBARRAETQ, ORIGEM, STATUS_ORIGEM, DTA_EVENTO_ORIGEM, DTA_CAPTURA, HASH_EVENTO, OBS
    ) VALUES (
      CD2.SQ_DD_SORTER_EVENTO_CTRL.NEXTVAL,
      P_CODBARRAETQ,
      'FECHAMENTO',
      'SEM_DADOS',
      SYSDATE,
      SYSDATE,
      P_CODBARRAETQ || '|FECHA|SEM_DADOS|' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
      'ETIQUETA NAO ENCONTRADA EM CORRELACAO/PENDENCIAS'
    );
    COMMIT;
END;
