-- =============================================================================
-- PROCEDURE: DD_PRC_BATCH_CARGA_SYNC
-- Exportado de CD2@2026-07-06 (fonte: banco remoto)
-- =============================================================================

CREATE OR REPLACE PROCEDURE       "DD_PRC_BATCH_CARGA_SYNC" AS
BEGIN
  MERGE INTO CD2.DD_SORTER_BATCH_CARGA_CTRL t
  USING (
    SELECT e.NROCARGA,
	   COUNT(DISTINCT c.CODBARRAETQ) AS VOLS_ELEGIVEIS
      FROM CD2.DDV_SORTER_CORRELACAO c
      JOIN CD2.DDV_SORTER_CORRELACAO_ENRIQ e
	ON e.CODBARRAETQ = c.CODBARRAETQ
      JOIN CONSINCO.MLO_INTEGRACAOSORTER i
	ON i.CODBARRAETQ = c.CODBARRAETQ
     WHERE NVL(i.INDOPERACAO, ' ') <> 'D'
       AND (
	     UPPER(TRIM(NVL(i.TIPOCARGA, 'E'))) = 'R'
	  OR NVL(e.QTD_EMB_SEPARADA, 0) > 0
	   )
       AND NOT EXISTS (
	     SELECT 1
	       FROM CD2.DD_SORTER_EVENTO_CTRL ev
	      WHERE ev.CODBARRAETQ = c.CODBARRAETQ
		AND ev.ORIGEM = 'ENVIO'
		AND ev.STATUS_ORIGEM IN ('ENVIADO_INVENT', 'ENVIO_AGG_INVENT')
	   )
     GROUP BY e.NROCARGA
  ) s
  ON (t.NROCARGA = s.NROCARGA)
  WHEN NOT MATCHED THEN
    INSERT (NROCARGA, STATUS, PRIORIDADE, VOLS_ELEGIVEIS, DTA_INCLUSAO, DTA_ULTIMO_CICLO)
    VALUES (s.NROCARGA, 'PENDENTE', 0, s.VOLS_ELEGIVEIS, SYSDATE, SYSDATE)
  WHEN MATCHED THEN
    UPDATE SET
      t.VOLS_ELEGIVEIS = s.VOLS_ELEGIVEIS,
      t.DTA_ULTIMO_CICLO = SYSDATE,
      t.STATUS = CASE
		   WHEN t.STATUS = 'CONCLUIDA' AND s.VOLS_ELEGIVEIS > 0 THEN 'PENDENTE'
		   WHEN t.STATUS = 'CONCLUIDA' THEN 'CONCLUIDA'
		   ELSE t.STATUS
		 END,
      t.WORKER_ID = CASE
		      WHEN t.STATUS = 'CONCLUIDA' AND s.VOLS_ELEGIVEIS > 0 THEN NULL
		      ELSE t.WORKER_ID
		    END;

  /* Cadastro corrigiu DUN/MAP: re-promove do fim da fila (PRIORIDADE=-1) quando existe
     volume elegivel com codacesso valido na view (nao SEM_COD_*). */
  UPDATE CD2.DD_SORTER_BATCH_CARGA_CTRL t
     SET PRIORIDADE = 0,
	 OBS = CASE
		 WHEN NVL(t.PRIORIDADE, 0) < 0 THEN 'DUN OK - RE-PROMOVIDA PARA FILA'
		 ELSE t.OBS
	       END
   WHERE NVL(t.PRIORIDADE, 0) < 0
     AND t.STATUS IN ('PENDENTE', 'PROCESSANDO')
     AND EXISTS (
	   SELECT 1
	     FROM CD2.DDV_SORTER_CORRELACAO c
	     JOIN CD2.DDV_SORTER_CORRELACAO_ENRIQ e
	       ON e.CODBARRAETQ = c.CODBARRAETQ
	     JOIN CONSINCO.MLO_INTEGRACAOSORTER i
	       ON i.CODBARRAETQ = c.CODBARRAETQ
	    WHERE e.NROCARGA = t.NROCARGA
	      AND NVL(i.INDOPERACAO, ' ') <> 'D'
	      AND (
		    UPPER(TRIM(NVL(i.TIPOCARGA, 'E'))) = 'R'
		 OR NVL(e.QTD_EMB_SEPARADA, 0) > 0
		  )
	      AND TRIM(NVL(e.CODACESSO_PRINCIPAL, ' ')) NOT LIKE 'SEM_COD_%'
	      AND NOT EXISTS (
		    SELECT 1
		      FROM CD2.DD_SORTER_EVENTO_CTRL ev
		     WHERE ev.CODBARRAETQ = c.CODBARRAETQ
		       AND ev.ORIGEM = 'ENVIO'
		       AND ev.STATUS_ORIGEM IN ('ENVIADO_INVENT', 'ENVIO_AGG_INVENT')
		  )
	 );

  /* DUN resolvido mas ainda com evento BLOQUEIO_SEM_CODACESSO: sobe prioridade para
     reprocesso (021 ignora bloqueio antigo quando codacesso ja e valido). */
  UPDATE CD2.DD_SORTER_BATCH_CARGA_CTRL t
     SET PRIORIDADE = GREATEST(NVL(t.PRIORIDADE, 0), 10),
	 STATUS = CASE
		    WHEN t.STATUS = 'CONCLUIDA' THEN 'PENDENTE'
		    ELSE t.STATUS
		  END,
	 WORKER_ID = CASE
		       WHEN t.STATUS = 'CONCLUIDA' THEN NULL
		       ELSE t.WORKER_ID
		     END,
	 OBS = 'DUN RESOLVIDO - AGUARDANDO REPROCESSO'
   WHERE EXISTS (
	   SELECT 1
	     FROM CD2.DDV_SORTER_CORRELACAO c
	     JOIN CD2.DDV_SORTER_CORRELACAO_ENRIQ e
	       ON e.CODBARRAETQ = c.CODBARRAETQ
	     JOIN CONSINCO.MLO_INTEGRACAOSORTER i
	       ON i.CODBARRAETQ = c.CODBARRAETQ
	    WHERE e.NROCARGA = t.NROCARGA
	      AND NVL(i.INDOPERACAO, ' ') <> 'D'
	      AND (
		    UPPER(TRIM(NVL(i.TIPOCARGA, 'E'))) = 'R'
		 OR NVL(e.QTD_EMB_SEPARADA, 0) > 0
		  )
	      AND TRIM(NVL(e.CODACESSO_PRINCIPAL, ' ')) NOT LIKE 'SEM_COD_%'
	      AND EXISTS (
		    SELECT 1
		      FROM CD2.DD_SORTER_EVENTO_CTRL evb
		     WHERE evb.CODBARRAETQ = c.CODBARRAETQ
		       AND evb.ORIGEM = 'ENVIO'
		       AND evb.STATUS_ORIGEM = 'BLOQUEIO_SEM_CODACESSO'
		  )
	      AND NOT EXISTS (
		    SELECT 1
		      FROM CD2.DD_SORTER_EVENTO_CTRL evs
		     WHERE evs.CODBARRAETQ = c.CODBARRAETQ
		       AND evs.ORIGEM = 'ENVIO'
		       AND evs.STATUS_ORIGEM IN ('ENVIADO_INVENT', 'ENVIO_AGG_INVENT')
		  )
	 );

  COMMIT;
END;
