-- =============================================================================
-- PROCEDURE: DD_PRC_BATCH_ENVIO_SHARD
-- Exportado de CD2@2026-07-01 (fonte: banco remoto)
-- =============================================================================

CREATE OR REPLACE PROCEDURE "DD_PRC_BATCH_ENVIO_SHARD" (
  P_NROCARGA    IN NUMBER,
  P_SHARD_TOTAL IN NUMBER,
  P_SHARD_ID    IN NUMBER,
  P_LIMIT       IN NUMBER DEFAULT 200
) AS
  V_ERR  VARCHAR2(4000);
  V_PEND NUMBER;
BEGIN
  IF P_NROCARGA IS NULL OR P_SHARD_TOTAL IS NULL OR P_SHARD_ID IS NULL THEN
    RAISE_APPLICATION_ERROR(-20002, 'P_NROCARGA, P_SHARD_TOTAL e P_SHARD_ID obrigatorios');
  END IF;
  IF P_SHARD_TOTAL < 1 OR P_SHARD_ID < 0 OR P_SHARD_ID >= P_SHARD_TOTAL THEN
    RAISE_APPLICATION_ERROR(-20003, 'P_SHARD_ID invalido');
  END IF;

  FOR R IN (
    SELECT ranked.CODBARRAETQ
      FROM (
	  SELECT b.CODBARRAETQ,
		 ROW_NUMBER() OVER (
		   ORDER BY b.prioridade_bloqueio, b.CODBARRAETQ
		 ) AS seq
	    FROM (
	      SELECT c.CODBARRAETQ,
		     CASE
		       WHEN EXISTS (
			 SELECT 1
			   FROM CD2.DD_SORTER_EVENTO_CTRL evb
			  WHERE evb.CODBARRAETQ = c.CODBARRAETQ
			    AND evb.ORIGEM = 'ENVIO'
			    AND evb.STATUS_ORIGEM = 'BLOQUEIO_SEM_CODACESSO'
		       ) THEN 1
		       ELSE 0
		     END AS prioridade_bloqueio,
		     ROW_NUMBER() OVER (
		       PARTITION BY c.CODBARRAETQ
		       ORDER BY c.CODBARRAETQ
		     ) AS dedupe_rn
		FROM CD2.DDV_SORTER_CORRELACAO c
		JOIN CD2.DDV_SORTER_CORRELACAO_ENRIQ e
		  ON e.CODBARRAETQ = c.CODBARRAETQ
		JOIN CONSINCO.MLO_INTEGRACAOSORTER i
		  ON i.CODBARRAETQ = c.CODBARRAETQ
	       WHERE e.NROCARGA = P_NROCARGA
		 AND MOD(ABS(ORA_HASH(c.CODBARRAETQ)), P_SHARD_TOTAL) = P_SHARD_ID
		 AND (
		       UPPER(TRIM(NVL(i.TIPOCARGA, 'E'))) = 'R'
		    OR NVL(e.QTD_EMB_SEPARADA, 0) > 0
		     )
		 AND NOT EXISTS (
		       SELECT 1
			 FROM CD2.DD_SORTER_EVENTO_CTRL ev
			WHERE ev.CODBARRAETQ = c.CODBARRAETQ
			  AND ev.ORIGEM = 'ENVIO'
			  AND ev.STATUS_ORIGEM IN ('ENVIADO_INVENT', 'ENVIO_AGG_INVENT')
		     )
	    ) b
	   WHERE b.dedupe_rn = 1
      ) ranked
     WHERE ranked.seq <= P_LIMIT
  ) LOOP
    BEGIN
      CD2.DD_PRC_ENVIA_C5_INVENT(P_CODBARRAETQ => R.CODBARRAETQ);
    EXCEPTION
      WHEN OTHERS THEN
	  ROLLBACK;
	  V_ERR := SUBSTR(SQLERRM, 1, 3500);
	  INSERT INTO CD2.DD_SORTER_EVENTO_CTRL (
	    ID_EVENTO, CODBARRAETQ, ORIGEM, STATUS_ORIGEM, DTA_EVENTO_ORIGEM, DTA_CAPTURA, HASH_EVENTO, OBS
	  ) VALUES (
	    CD2.SQ_DD_SORTER_EVENTO_CTRL.NEXTVAL,
	    R.CODBARRAETQ,
	    'BATCH',
	    'ERRO_ENVIO',
	    SYSDATE,
	    SYSDATE,
	    R.CODBARRAETQ || '|BATCH|ERRO_ENV|' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
	    V_ERR
	  );
	  COMMIT;
    END;
  END LOOP;

  SELECT COUNT(DISTINCT c.CODBARRAETQ)
    INTO V_PEND
    FROM CD2.DDV_SORTER_CORRELACAO c
    JOIN CD2.DDV_SORTER_CORRELACAO_ENRIQ e
      ON e.CODBARRAETQ = c.CODBARRAETQ
    JOIN CONSINCO.MLO_INTEGRACAOSORTER i
      ON i.CODBARRAETQ = c.CODBARRAETQ
   WHERE e.NROCARGA = P_NROCARGA
     AND NVL(i.INDOPERACAO, ' ') <> 'D'
     AND (
	   UPPER(TRIM(NVL(i.TIPOCARGA, 'E'))) = 'R'
	OR NVL(e.QTD_EMB_SEPARADA, 0) > 0
	 )
     AND NOT EXISTS (
	   SELECT 1
	     FROM CD2.DD_SORTER_EVENTO_CTRL ev
	    WHERE ev.CODBARRAETQ = c.CODBARRAETQ
	      AND ev.ORIGEM = 'ENVIO'
	      AND ev.STATUS_ORIGEM IN ('ENVIADO_INVENT', 'ENVIO_AGG_INVENT')
	 );

  UPDATE CD2.DD_SORTER_BATCH_CARGA_CTRL
     SET VOLS_ELEGIVEIS = V_PEND,
	 DTA_ULTIMO_CICLO = SYSDATE,
	 WORKER_ID = 'SHARD' || TO_CHAR(P_SHARD_TOTAL),
	 OBS = 'shard ' || TO_CHAR(P_SHARD_ID) || '/' || TO_CHAR(P_SHARD_TOTAL),
	 STATUS = CASE WHEN V_PEND = 0 THEN 'CONCLUIDA' ELSE STATUS END,
	 DTA_CONCLUSAO = CASE WHEN V_PEND = 0 THEN SYSDATE ELSE DTA_CONCLUSAO END
   WHERE NROCARGA = P_NROCARGA;

  COMMIT;
END;
