-- =============================================================================
-- PROCEDURE: DD_PRC_BATCH_RETORNO_V2
-- Exportado de CD2@2026-07-01 (fonte: banco remoto)
-- =============================================================================

CREATE OR REPLACE PROCEDURE "DD_PRC_BATCH_RETORNO_V2" (
  P_PREFIXO_ETIQUETA IN VARCHAR2 DEFAULT '%',
  P_LIMIT	     IN NUMBER	 DEFAULT 2000,
  P_NROCARGA_MIN     IN NUMBER	 DEFAULT NULL,
  P_WORKER_ID	     IN NUMBER	 DEFAULT NULL,
  P_TOTAL_WORKERS    IN NUMBER	 DEFAULT NULL
) AS
  V_ERR	      VARCHAR2(4000);
  V_N_RET	NUMBER := 0;
  V_SKIP_CAPTURA NUMBER;
  V_SKIP_RECON   NUMBER;
BEGIN
  /* Fase 2 - RETORNO/FECHAMENTO: ja enviadas; atualiza C5 sem reenviar GPT.
     Performance (sem mudar regra de negocio):
     - Selecao via CORRELACAO + MLO (sem DDV_SORTER_CORRELACAO_ENRIQ).
     - FECHA somente INDUZIDO/RETORNO_PRODUTO (gate identico ao 022).
     - Pula CAPTURA/RECON quando ja reconciliado OK.
     - Workers opcionais: MOD(ORA_HASH(etq), P_TOTAL_WORKERS) = P_WORKER_ID.
     - Prioridade: elegiveis primeiro; cargas antigas (NROCARGA ASC) nao ficam para tras. */
  FOR R IN (
    SELECT ranked.CODBARRAETQ,
	   ranked.STATUS_ELEGIVEL
      FROM (
	SELECT b.CODBARRAETQ,
	       b.STATUS_ELEGIVEL,
	       ROW_NUMBER() OVER (
		 ORDER BY b.prioridade_fecha,
			  b.nrocarga ASC,
			  b.CODBARRAETQ
	       ) AS seq
	  FROM (
	    SELECT c.CODBARRAETQ,
		   c.NROCARGA AS nrocarga,
		   NVL(c.STATUS_SORTER, c.STATUS_VOLUME) AS STATUS_ELEGIVEL,
		   CASE
		     WHEN NVL(c.STATUS_SORTER, c.STATUS_VOLUME) IN (
			    'RETORNO_PRODUTO', 'INDUZIDO'
			  ) THEN 0
		     ELSE 1
		   END AS prioridade_fecha,
		   ROW_NUMBER() OVER (
		     PARTITION BY c.CODBARRAETQ
		     ORDER BY c.CODBARRAETQ
		   ) AS dedupe_rn
	      FROM CD2.DDV_SORTER_CORRELACAO c
	      JOIN CONSINCO.MLO_INTEGRACAOSORTER i
		ON i.CODBARRAETQ = c.CODBARRAETQ
	      LEFT JOIN CONSINCO.MLO_MONTAGEMSORTER m
		ON m.CODBARRAETQ = c.CODBARRAETQ
	     WHERE c.CODBARRAETQ LIKE P_PREFIXO_ETIQUETA
	       AND (P_NROCARGA_MIN IS NULL OR c.NROCARGA >= P_NROCARGA_MIN)
	       AND (
		     P_TOTAL_WORKERS IS NULL
		     OR P_WORKER_ID IS NULL
		     OR MOD(ORA_HASH(c.CODBARRAETQ), P_TOTAL_WORKERS) = P_WORKER_ID
		   )
	       AND NVL(TRIM(i.INDOPERACAO), ' ') <> 'D'
	       AND (
		     EXISTS (
		       SELECT 1
			 FROM CD2.DD_SORTER_EVENTO_CTRL ev
			WHERE ev.CODBARRAETQ = c.CODBARRAETQ
			  AND ev.ORIGEM = 'ENVIO'
			  AND ev.STATUS_ORIGEM IN (
				'ENVIADO_INVENT', 'ENVIO_AGG_INVENT'
			      )
		     )
		     OR (
		       NVL(c.STATUS_SORTER, c.STATUS_VOLUME) IN (
			 'RETORNO_PRODUTO', 'INDUZIDO'
		       )
		       AND EXISTS (
			 SELECT 1
			   FROM CD2.DD_SORTER_EVENTO_CTRL ev2
			  WHERE ev2.CODBARRAETQ = c.CODBARRAETQ
			    AND ev2.ORIGEM = 'ENVIO'
			    AND ev2.STATUS_ORIGEM = 'ERRO_DESTINO_INTEGRADO'
			    AND NVL(ev2.OBS, ' ') LIKE 'GPT JA INTEGRADO%'
		       )
		       AND NOT EXISTS (
			 SELECT 1
			   FROM CD2.DD_SORTER_EVENTO_CTRL ev3
			  WHERE ev3.CODBARRAETQ = c.CODBARRAETQ
			    AND ev3.ORIGEM = 'ENVIO'
			    AND ev3.STATUS_ORIGEM IN (
			      'ENVIADO_INVENT', 'ENVIO_AGG_INVENT'
			    )
		       )
		     )
		   )
	       AND NOT (
		     NVL(i.INDPROCESSADO, 'N') = 'S'
		 AND NVL(m.INDPROCESSADO, 'N') = 'S'
		   )
	  ) b
	 WHERE b.dedupe_rn = 1
      ) ranked
     WHERE ranked.seq <= P_LIMIT
  ) LOOP
    BEGIN
      IF R.STATUS_ELEGIVEL IN ('INDUZIDO', 'RETORNO_PRODUTO') THEN
	SELECT COUNT(*)
	  INTO V_SKIP_RECON
	  FROM CD2.DD_SORTER_EVENTO_CTRL ev
	 WHERE ev.CODBARRAETQ = R.CODBARRAETQ
	   AND ev.ORIGEM = 'RECON'
	   AND ev.STATUS_ORIGEM = 'OK';
	IF V_SKIP_RECON = 0 THEN
	  SELECT COUNT(*)
	    INTO V_SKIP_CAPTURA
	    FROM CD2.DD_SORTER_EVENTO_CTRL ev
	   WHERE ev.CODBARRAETQ = R.CODBARRAETQ
	     AND ev.ORIGEM = 'INVENT'
	     AND ev.STATUS_ORIGEM = R.STATUS_ELEGIVEL;
	  IF V_SKIP_CAPTURA = 0 THEN
	    CD2.DD_PRC_CAPTURA_STATUS_INVENT(
	      P_CODBARRAETQ => R.CODBARRAETQ,
	      P_LIMIT => 50
	    );
	  END IF;
	  CD2.DD_PRC_RECONCILIA_ETIQUETA(P_CODBARRAETQ => R.CODBARRAETQ);
	END IF;
	CD2.DD_PRC_FECHA_C5_ETIQUETA(P_CODBARRAETQ => R.CODBARRAETQ);
      END IF;
      V_N_RET := V_N_RET + 1;
    EXCEPTION
      WHEN OTHERS THEN
	ROLLBACK;
	V_ERR := SUBSTR(SQLERRM, 1, 3500);
	BEGIN
	  INSERT INTO CD2.DD_SORTER_EVENTO_CTRL (
	    ID_EVENTO, CODBARRAETQ, ORIGEM, STATUS_ORIGEM, DTA_EVENTO_ORIGEM, DTA_CAPTURA, HASH_EVENTO, OBS
	  ) VALUES (
	    CD2.SQ_DD_SORTER_EVENTO_CTRL.NEXTVAL,
	    R.CODBARRAETQ,
	    'BATCH',
	    'ERRO_RETORNO',
	    SYSDATE,
	    SYSDATE,
	    R.CODBARRAETQ || '|BATCH|ERRO_RET|' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
	    V_ERR
	  );
	  COMMIT;
	EXCEPTION
	  WHEN DUP_VAL_ON_INDEX THEN
	    NULL;
	END;
    END;
  END LOOP;
END;
