-- =============================================================================
-- PROCEDURE: DD_PRC_BATCH_RETORNO_V3
-- Exportado de CD2@2026-07-23
-- Fix: loop só chama FECHA (CAPTURA/RECON @INVENT travava o worker sem mudar elegibilidade)
-- =============================================================================

CREATE OR REPLACE PROCEDURE       "DD_PRC_BATCH_RETORNO_V3" (
  P_PREFIXO_ETIQUETA IN VARCHAR2 DEFAULT '%',
  P_LIMIT	     IN NUMBER	 DEFAULT 2000,
  P_NROCARGA_MIN     IN NUMBER	 DEFAULT NULL,
  P_WORKER_ID	     IN NUMBER	 DEFAULT NULL,
  P_TOTAL_WORKERS    IN NUMBER	 DEFAULT NULL
) AS
  V_ERR	      VARCHAR2(4000);
  V_N_RET	NUMBER := 0;
  TYPE T_ETQ IS TABLE OF VARCHAR2(40) INDEX BY PLS_INTEGER;
  V_ETQS	T_ETQ;
BEGIN
  CD2.DD_PKG_FECHA_CACHE.CLEAR_ALL;

  DELETE FROM CD2.DD_SORTER_GPT_RETORNO_FILA;

  EXECUTE IMMEDIATE '
    INSERT INTO CD2.DD_SORTER_GPT_RETORNO_FILA (EMPRESA, ONDA, SEQPRODUTO, LOJA, DATA_FECHAMENTO)
    SELECT r.EMPRESA,
	   r.ONDA,
	   r.SEQPRODUTO,
	   r.LOJA,
	   MIN(r.DATA_FECHAMENTO)
      FROM "GPT_RETORNO_MONTAGEM_PALETES"@INVENT r
     WHERE r.DATA_FECHAMENTO IS NOT NULL
       AND NOT EXISTS (
	     SELECT 1
	       FROM CD2.DD_SORTER_VINCULO_RETORNO_ETQ v
	      WHERE v.ID_GPT_RETORNO = r.ID_GPT_RETORNO_MONTAGEM_PALETES
	   )
     GROUP BY r.EMPRESA, r.ONDA, r.SEQPRODUTO, r.LOJA';

  /* Mesma elegibilidade de antes; materializa a lista e só então chama FECHA
     (evita cursor aberto + CAPTURA/RECON no @INVENT que segurava o job). */
  SELECT ranked.CODBARRAETQ
    BULK COLLECT INTO V_ETQS
    FROM (
      SELECT b.CODBARRAETQ,
	     ROW_NUMBER() OVER (
	       ORDER BY b.gpt_fecha ASC,
			b.nrocarga ASC,
			b.CODBARRAETQ
	     ) AS seq
	FROM (
	  SELECT c.CODBARRAETQ,
		 c.NROCARGA AS nrocarga,
		 gpt.DATA_FECHAMENTO AS gpt_fecha,
		 ROW_NUMBER() OVER (
		   PARTITION BY c.CODBARRAETQ
		   ORDER BY gpt.DATA_FECHAMENTO, c.CODBARRAETQ
		 ) AS dedupe_rn
	    FROM CD2.DD_SORTER_GPT_RETORNO_FILA gpt
	    JOIN CONSINCO.MLO_INTEGRACAOSORTER i
	      ON i.NROEMPRESA = gpt.EMPRESA
	     AND i.NROCARGA = gpt.ONDA
	     AND i.SEQPRODUTO = gpt.SEQPRODUTO
	    JOIN CONSINCO.MLO_TIPESPECIE ts
	      ON ts.NROEMPRESA = i.NROEMPRESA
	     AND ts.TIPESPECIE = i.TIPESPECIE
	    JOIN CD2.DDV_SORTER_CORRELACAO c
	      ON c.CODBARRAETQ = i.CODBARRAETQ
	    LEFT JOIN CONSINCO.MLO_MONTAGEMSORTER m
	      ON m.CODBARRAETQ = c.CODBARRAETQ
	   WHERE c.CODBARRAETQ LIKE P_PREFIXO_ETIQUETA
	     AND (P_NROCARGA_MIN IS NULL OR c.NROCARGA >= P_NROCARGA_MIN)
	     AND (
		   P_TOTAL_WORKERS IS NULL
		   OR P_WORKER_ID IS NULL
		   OR MOD(ORA_HASH(c.CODBARRAETQ), P_TOTAL_WORKERS) = P_WORKER_ID
		 )
	     AND NVL(TRIM(i.INDOPERACAO), ' ') <> 'D'
	     AND NVL(c.STATUS_SORTER, c.STATUS_VOLUME) IN (
		   'RETORNO_PRODUTO', 'INDUZIDO'
		 )
	     AND (
		   (gpt.LOJA <> gpt.EMPRESA
		    AND REGEXP_LIKE(TRIM(ts.DESCTIPESPECIE), '^[0-9]+')
		    AND gpt.LOJA = TO_NUMBER(
			  REGEXP_SUBSTR(TRIM(ts.DESCTIPESPECIE), '^[0-9]+')
			))
		   OR (gpt.LOJA = gpt.EMPRESA)
		 )
	     AND (
		   EXISTS (
		     SELECT 1
		       FROM CD2.DD_SORTER_EVENTO_CTRL ev
		      WHERE ev.CODBARRAETQ = c.CODBARRAETQ
			AND ev.ORIGEM = 'ENVIO'
			AND ev.STATUS_ORIGEM IN (
			      'ENVIADO_INVENT', 'ENVIO_AGG_INVENT'
			)
		   )
		   OR (
		     EXISTS (
		       SELECT 1
			 FROM CD2.DD_SORTER_EVENTO_CTRL ev2
			WHERE ev2.CODBARRAETQ = c.CODBARRAETQ
			  AND ev2.ORIGEM = 'ENVIO'
			  AND ev2.STATUS_ORIGEM = 'ERRO_DESTINO_INTEGRADO'
			  AND NVL(ev2.OBS, ' ') LIKE 'GPT JA INTEGRADO%'
		     )
		     AND NOT EXISTS (
		       SELECT 1
			 FROM CD2.DD_SORTER_EVENTO_CTRL ev3
			WHERE ev3.CODBARRAETQ = c.CODBARRAETQ
			  AND ev3.ORIGEM = 'ENVIO'
			  AND ev3.STATUS_ORIGEM IN (
			    'ENVIADO_INVENT', 'ENVIO_AGG_INVENT'
			  )
		     )
		   )
		 )
	     AND NOT (
		   NVL(i.INDPROCESSADO, 'N') = 'S'
	       AND NVL(m.INDPROCESSADO, 'N') = 'S'
		 )
	     AND NOT EXISTS (
		   SELECT 1
		     FROM CD2.DD_SORTER_EVENTO_CTRL evf
		    WHERE evf.CODBARRAETQ = c.CODBARRAETQ
		      AND evf.ORIGEM = 'FECHAMENTO'
		      AND evf.STATUS_ORIGEM = 'C5_FECHADO'
		 )
	) b
       WHERE b.dedupe_rn = 1
    ) ranked
   WHERE ranked.seq <= P_LIMIT;

  IF V_ETQS.COUNT > 0 THEN
    FOR I IN V_ETQS.FIRST .. V_ETQS.LAST LOOP
      BEGIN
	CD2.DD_PRC_FECHA_C5_ETIQUETA(P_CODBARRAETQ => V_ETQS(I));
	V_N_RET := V_N_RET + 1;
      EXCEPTION
	WHEN OTHERS THEN
	  ROLLBACK;
	  V_ERR := SUBSTR(SQLERRM, 1, 3500);
	  BEGIN
	    INSERT INTO CD2.DD_SORTER_EVENTO_CTRL (
	      ID_EVENTO, CODBARRAETQ, ORIGEM, STATUS_ORIGEM, DTA_EVENTO_ORIGEM, DTA_CAPTURA, HASH_EVENTO, OBS
	    ) VALUES (
	      CD2.SQ_DD_SORTER_EVENTO_CTRL.NEXTVAL,
	      V_ETQS(I),
	      'BATCH',
	      'ERRO_RETORNO',
	      SYSDATE,
	      SYSDATE,
	      V_ETQS(I) || '|BATCH|ERRO_RET|' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
	      V_ERR
	    );
	    COMMIT;
	  EXCEPTION
	    WHEN DUP_VAL_ON_INDEX THEN
	      NULL;
	  END;
      END;
    END LOOP;
  END IF;
END;
